import Link from 'next/link'
import { notFound } from 'next/navigation'

import { ReportPreview } from '@/components/indicare/report-preview'
import { Card, PageHeader, SectionHeader, StatusBadge } from '@/components/indicare/ui'
import { indicareData } from '@/lib/indicare/demo-data'
import { buildReportDraft } from '@/lib/indicare/reports'
import { fullName, getStaffById, getYoungPersonById } from '@/lib/indicare/selectors'

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const report = indicareData.reports.find((item) => item.id === id)
  if (!report) notFound()

  const draft = buildReportDraft(report)
  const person = getYoungPersonById(report.youngPersonId)
  const generatedBy = getStaffById(report.generatedBy)

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Report draft" title={report.title} description={`${report.type} for ${person ? fullName(person) : report.youngPersonId}. ${report.dateRangeStart} to ${report.dateRangeEnd}.`} action={<Link href="/assistant" className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-500/30">Improve wording</Link>} />
      <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <Card>
          <SectionHeader eyebrow="Generated draft" title="Structured report preview" description="Sections are built from linked records, not one hard-coded paragraph." />
          <ReportPreview sections={draft.sections} />
        </Card>
        <Card>
          <SectionHeader eyebrow="Metadata" title="Report details" />
          <div className="space-y-4 text-sm leading-7 text-slate-600">
            <StatusBadge value={report.status} />
            <p><strong className="text-slate-950">Generated by:</strong> {generatedBy ? fullName(generatedBy) : report.generatedBy}</p>
            <p><strong className="text-slate-950">Created:</strong> {new Date(report.createdAt).toLocaleString('en-GB')}</p>
            <p><strong className="text-slate-950">Updated:</strong> {new Date(report.updatedAt).toLocaleString('en-GB')}</p>
            <p><strong className="text-slate-950">Assistant actions:</strong> draft report, improve wording, check missing sections, make Ofsted-ready.</p>
          </div>
        </Card>
      </section>
    </div>
  )
}
