(function(){
  var modes={
    assistant:{title:'Assistant',model:'ChatGPT-style workspace',hero:'Think, write and work naturally.',copy:'A calm professional AI assistant for adults working in residential children\'s homes.',starters:['Help me think through a difficult shift calmly.','Turn these notes into a professional handover.','Help me prepare for supervision tomorrow.','Rewrite this email professionally.']},
    connect:{title:'Connect',model:'Outlook + Teams + AI',hero:'Communication with intelligence built in.',copy:'Draft replies, summarise meetings, prepare agendas and extract follow-up actions.',starters:['Draft a professional reply.','Summarise these meeting notes.','Create a team meeting agenda.','Extract follow-up actions.']},
    notes:{title:'I-Notes',model:'Beam / Magic Notes',hero:'Capture thoughts. Transform them.',copy:'Speak, paste or type rough notes and turn them into professional summaries, supervision prep or actions.',starters:['Turn this into supervision prep.','Create a reflective summary.','Extract actions from these notes.','Make this sound professional.']},
    docs:{title:'Docs',model:'Pages / Word + AI',hero:'Professional writing, structured by AI.',copy:'Templates and writing support for supervision, meetings, Ofsted preparation, provider responses and leadership work.',starters:['Open a supervision template.','Create an Ofsted preparation note.','Improve this document.','Create a professional development plan.']},
    intelligence:{title:'Intelligence',model:'Immersive conversational reasoning',hero:'Ask anything. Think deeply. Decide clearly.',copy:'A spacious reasoning environment for adult professional reflection, preparation and decision support.',starters:['Challenge my assumptions on this issue.','Help me prioritise calmly.','Think through this leadership decision.','Prepare me for Ofsted tomorrow.']}
  };
  var state={mode:localStorage.getItem('ic.ai.mode')||'assistant',messages:read('ic.ai.messages',[]),notes:localStorage.getItem('ic.ai.notes')||'',docTitle:localStorage.getItem('ic.ai.docTitle')||'Untitled professional document',docBody:localStorage.getItem('ic.ai.docBody')||'',actions:read('ic.ai.actions',[]),busy:false};
  function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch(e){return f;}}
  function save(){localStorage.setItem('ic.ai.mode',state.mode);localStorage.setItem('ic.ai.messages',JSON.stringify(state.messages.slice(-120)));localStorage.setItem('ic.ai.notes',state.notes);localStorage.setItem('ic.ai.docTitle',state.docTitle);localStorage.setItem('ic.ai.docBody',state.docBody);localStorage.setItem('ic.ai.actions',JSON.stringify(state.actions.slice(0,80)));}
  function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function root(){return document.getElementById('indicareAiRoot');}
  function scoped(){return state.messages.filter(function(m){return m.mode===state.mode;});}
  function layout(){var cfg=modes[state.mode];return '<div class="ai-app '+(state.mode==='intelligence'?'is-dark':'')+'">'+rail()+ '<main class="ai-main"><header class="ai-header"><div><p>'+esc(cfg.model)+'</p><h1>'+esc(cfg.title)+'</h1><span>'+esc(cfg.copy)+'</span></div><div class="ai-header-actions"><button data-action="new">New thread</button><button data-action="save-action">Save action</button></div></header>'+surface()+composer()+'</main>'+panel()+'</div>';}
  function rail(){return '<aside class="ai-rail"><div class="ai-brand"><div>IC</div><span><strong>IndiCare AI</strong><small>Isolated intelligence runtime</small></span></div><nav>'+Object.keys(modes).map(function(k){var m=modes[k];return '<button class="'+(state.mode===k?'active':'')+'" data-mode="'+k+'"><b>'+m.title.charAt(0)+'</b><span><strong>'+esc(m.title)+'</strong><small>'+esc(m.model)+'</small></span></button>';}).join('')+'</nav><section><strong>Boundary protected</strong><small>AI workspace runs separately from the OS command surface.</small></section></aside>';}
  function surface(){if(state.mode==='connect')return connect();if(state.mode==='notes')return notes();if(state.mode==='docs')return docs();return conversation();}
  function conversation(){var cfg=modes[state.mode],msgs=scoped();return '<section class="ai-conversation"><div class="ai-feed">'+(msgs.length?messages(msgs):hero(cfg))+(state.busy?thinking():'')+'</div></section>';}
  function hero(cfg){return '<div class="ai-hero"><div class="ai-orb">IC</div><h2>'+esc(cfg.hero)+'</h2><p>'+esc(cfg.copy)+'</p><div class="ai-starters">'+cfg.starters.map(function(s){return '<button data-starter="'+esc(s)+'"><strong>'+esc(s)+'</strong><span>Start</span></button>';}).join('')+'</div></div>';}
  function messages(list){return list.map(function(m){return '<article class="ai-message '+m.role+'"><div>'+(m.role==='user'?'You':'AI')+'</div><p>'+esc(m.content)+'</p></article>';}).join('');}
  function connect(){return '<section class="ai-workspace"><div class="ai-card wide"><p>Connect</p><h2>Outlook + Teams style communication</h2><textarea id="connectInput" placeholder="Paste an email, team message, meeting note or agenda items..."></textarea><div class="ai-actions"><button data-connect="Draft a professional reply">Draft reply</button><button data-connect="Summarise and extract actions">Summarise</button><button data-connect="Create a meeting agenda">Agenda</button></div></div><div class="ai-card"><h3>Communication tools</h3><ul><li>AI replies</li><li>Meeting summaries</li><li>Follow-up extraction</li><li>Team coordination</li></ul></div></section>';}
  function notes(){return '<section class="ai-workspace"><div class="ai-card wide"><p>I-Notes</p><h2>Beam-style cognitive capture</h2><textarea id="notesInput" placeholder="Type or paste rough notes...">'+esc(state.notes)+'</textarea><div class="ai-actions"><button data-note="professional summary">Summary</button><button data-note="supervision preparation">Supervision prep</button><button data-note="meeting minutes and actions">Minutes</button><button data-note="reflective debrief">Debrief</button></div></div><div class="ai-card"><h3>Transform into</h3><ul><li>Summaries</li><li>Actions</li><li>Reflection</li><li>Preparation</li></ul></div></section>';}
  function docs(){return '<section class="ai-workspace docs"><div class="ai-card templates"><h3>Templates</h3><button data-template="Supervision preparation">Supervision</button><button data-template="Team meeting agenda">Meeting agenda</button><button data-template="Ofsted preparation note">Ofsted prep</button><button data-template="Professional development plan">Development plan</button></div><div class="ai-card wide"><input id="docTitle" value="'+esc(state.docTitle)+'"><textarea id="docBody" placeholder="Start writing...">'+esc(state.docBody)+'</textarea><div class="ai-actions"><button data-doc="Improve">Improve</button><button data-doc="Strengthen the professional tone of">Tone</button><button data-doc="Structure">Structure</button></div></div></section>';}
  function panel(){return '<aside class="ai-panel"><h2>Workspace memory</h2><p>Local AI workspace memory only. OS records remain separate.</p><div class="ai-stat">'+state.messages.length+' messages</div><div class="ai-stat">'+state.actions.length+' actions</div><h3>Actions</h3>'+((state.actions.length?state.actions.slice(0,6).map(function(a){return '<button class="ai-action" data-done="'+a.id+'">'+esc(a.title)+'</button>';}).join(''):'<p class="muted">No saved actions yet.</p>'))+'</aside>';}
  function composer(){return '<div class="ai-composer"><textarea id="prompt" placeholder="Message IndiCare AI..."></textarea><div><button data-action="voice">Voice</button><button data-action="send">Send</button></div></div>';}
  function thinking(){return '<div class="ai-thinking"><span></span><span></span><span></span></div>';}
  function render(){var r=root();if(r)r.innerHTML=layout();}
  function promptValue(){var el=document.getElementById('prompt');return el?el.value.trim():'';}
  function addAction(title){if(!title)return;state.actions.unshift({id:'a'+Date.now(),title:title,mode:state.mode});save();render();}
  async function send(text){var clean=String(text||promptValue()).trim();if(!clean||state.busy)return;state.messages.push({role:'user',mode:state.mode,content:clean});state.busy=true;save();render();var answer='';try{var res=await fetch('/assistant/general-safe',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'['+state.mode.toUpperCase()+'] '+clean,response_mode:state.mode==='intelligence'?'deep':'balanced',history:scoped().slice(-10)})});var data=await res.json();answer=data.answer||data.response||'I am here. Tell me what you want to work through.';}catch(e){answer='I could not connect to the assistant service just now. '+(e.message||e);}state.messages.push({role:'assistant',mode:state.mode,content:answer});state.busy=false;save();render();}
  function bind(){document.body.addEventListener('click',function(e){var mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.getAttribute('data-mode');save();render();return;}var starter=e.target.closest('[data-starter]');if(starter){send(starter.getAttribute('data-starter'));return;}var action=e.target.closest('[data-action]');if(action){var a=action.getAttribute('data-action');if(a==='send')send();if(a==='new'){state.messages=state.messages.filter(function(m){return m.mode!==state.mode;});save();render();}if(a==='save-action')addAction(promptValue()||'Follow up');return;}var c=e.target.closest('[data-connect]');if(c){var v=document.getElementById('connectInput');send(c.getAttribute('data-connect')+': '+(v?v.value:''));return;}var n=e.target.closest('[data-note]');if(n){var v=document.getElementById('notesInput');state.notes=v?v.value:state.notes;send('Transform these notes into '+n.getAttribute('data-note')+': '+state.notes);return;}var d=e.target.closest('[data-doc]');if(d){var t=document.getElementById('docTitle'),b=document.getElementById('docBody');state.docTitle=t?t.value:state.docTitle;state.docBody=b?b.value:state.docBody;send(d.getAttribute('data-doc')+' this document: '+state.docTitle+'\n\n'+state.docBody);return;}var tpl=e.target.closest('[data-template]');if(tpl){state.docTitle=tpl.getAttribute('data-template');state.docBody='Purpose\n\nKey points\n\nReflection\n\nActions\n\nReview';save();render();return;}});document.body.addEventListener('input',function(e){if(e.target.id==='notesInput')state.notes=e.target.value;if(e.target.id==='docTitle')state.docTitle=e.target.value;if(e.target.id==='docBody')state.docBody=e.target.value;save();});document.body.addEventListener('keydown',function(e){if(e.target.id==='prompt'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});}
  function mount(){render();bind();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
