(function(){
  if(window.__IndiCareRealtimeWebRTCInstalled)return;
  window.__IndiCareRealtimeWebRTCInstalled=true;
  var pc=null,dc=null,mic=null,audio=null,connecting=false,connected=false;
  function emit(type,detail){window.dispatchEvent(new CustomEvent('indicare:realtime-webrtc',{detail:Object.assign({type:type},detail||{})}));}
  function cls(){document.body.classList.toggle('ai-live-realtime',connected);document.body.classList.toggle('ai-live-connecting',connecting);}
  function memory(){try{return JSON.stringify((window.IndiCareAI&&window.IndiCareAI.summary&&window.IndiCareAI.summary())||{}).slice(0,4000);}catch(e){return '';}}
  function token(payload){var s=payload&&payload.session?payload.session:payload;return s&&s.client_secret&&(s.client_secret.value||s.client_secret)||null;}
  async function session(){var profile={};try{profile=JSON.parse(localStorage.getItem('ic.ai.profile')||'{}');}catch(e){}var r=await fetch('/assistant/realtime/session',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'intelligence',voice:profile.realtime_voice||'shimmer',profile:profile,memory_summary:memory(),conversation_id:localStorage.getItem('ic.ai.thread')||'default'})});if(!r.ok)throw new Error('session '+r.status);return await r.json();}
  function send(obj){try{if(dc&&dc.readyState==='open')dc.send(JSON.stringify(obj));}catch(e){}}
  function push(role,text){if(!text)return;if(window.IndiCareRealtime&&window.IndiCareRealtime.pushTranscript)window.IndiCareRealtime.pushTranscript(role,text);emit('transcript',{role:role,text:text});}
  function handle(raw){var e;try{e=JSON.parse(raw);}catch(x){return;}emit('event',e);if(window.IndiCareRealtime){if(e.type==='input_audio_buffer.speech_started'){window.IndiCareRealtime.listen(true);window.IndiCareRealtime.speak(false);}if(e.type==='input_audio_buffer.speech_stopped'){window.IndiCareRealtime.listen(false);window.IndiCareRealtime.think(true);}if(e.type==='response.audio.delta'){window.IndiCareRealtime.think(false);window.IndiCareRealtime.speak(true);}if(e.type==='response.done'||e.type==='response.audio.done'){window.IndiCareRealtime.speak(false);window.IndiCareRealtime.listen(true);}}
    if(e.type==='conversation.item.input_audio_transcription.completed')push('user',e.transcript||'');
    if(e.type==='response.audio_transcript.done')push('assistant',e.transcript||'');
    if(e.type==='response.audio_transcript.delta')emit('assistant_delta',{text:e.delta||''});
  }
  async function connect(){if(connected||connecting)return true;connecting=true;cls();try{var payload=await session();var key=token(payload);if(!key)throw new Error('missing realtime key');pc=new RTCPeerConnection();audio=document.getElementById('indicareRealtimeAudio')||document.createElement('audio');audio.id='indicareRealtimeAudio';audio.autoplay=true;audio.playsInline=true;audio.style.display='none';document.body.appendChild(audio);pc.ontrack=function(ev){audio.srcObject=ev.streams[0];};mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});mic.getTracks().forEach(function(t){pc.addTrack(t,mic);});dc=pc.createDataChannel('oai-events');dc.onopen=function(){connected=true;connecting=false;cls();send({type:'session.update',session:{turn_detection:{type:'server_vad',threshold:.5,prefix_padding_ms:300,silence_duration_ms:650},input_audio_transcription:{model:'whisper-1'}}});emit('ready',payload);};dc.onmessage=function(ev){handle(ev.data);};var offer=await pc.createOffer();await pc.setLocalDescription(offer);var model=payload.model||'gpt-4o-realtime-preview';var answer=await fetch('https://api.openai.com/v1/realtime?model='+encodeURIComponent(model),{method:'POST',body:offer.sdp,headers:{Authorization:'Bearer '+key,'Content-Type':'application/sdp'}});if(!answer.ok)throw new Error('sdp '+answer.status);await pc.setRemoteDescription({type:'answer',sdp:await answer.text()});return true;}catch(err){connecting=false;connected=false;cls();emit('fallback',{error:err.message||String(err)});return false;}}
  function disconnect(){try{if(dc)dc.close();}catch(e){}try{if(pc)pc.close();}catch(e){}try{if(mic)mic.getTracks().forEach(function(t){t.stop();});}catch(e){}pc=null;dc=null;mic=null;connected=false;connecting=false;cls();}
  function interrupt(){send({type:'response.cancel'});if(window.IndiCareVoice&&window.IndiCareVoice.interrupt)window.IndiCareVoice.interrupt();}
  window.IndiCareRealtimeWebRTC={connect:connect,disconnect:disconnect,interrupt:interrupt,send:send,isConnected:function(){return connected;}};
})();