export const els = {
  app: document.getElementById("app"),

  selectorScreen: document.getElementById("selectorScreen"),
  selectorSearch: document.getElementById("selectorSearch"),
  selectorRefreshBtn: document.getElementById("selectorRefreshBtn"),
  selectorList: document.getElementById("selectorList"),

  workspaceScreen: document.getElementById("workspaceScreen"),
  homeBtn: document.getElementById("homeBtn"),
  mobileHomeBtn: document.getElementById("mobileHomeBtn"),
  logoBtn: document.getElementById("logoBtn"),
  refreshBtn: document.getElementById("refreshBtn"),

  personAvatar: document.getElementById("personAvatar"),
  personName: document.getElementById("personName"),
  personMeta: document.getElementById("personMeta"),

  mobilePersonAvatar: document.getElementById("mobilePersonAvatar"),
  mobilePersonName: document.getElementById("mobilePersonName"),
  mobilePersonMeta: document.getElementById("mobilePersonMeta"),

  profileSnapshotPhotoWrap: document.getElementById("profileSnapshotPhotoWrap"),
  profileSnapshotName: document.getElementById("profileSnapshotName"),
  profileSnapshotMeta: document.getElementById("profileSnapshotMeta"),
  profileOpenBtn: document.getElementById("profileOpenBtn"),
  profilePhotoUploadBtn: document.getElementById("profilePhotoUploadBtn"),

  pageTitle: document.getElementById("pageTitle"),
  pageSubtitle: document.getElementById("pageSubtitle"),
  heroQuickActions: document.getElementById("heroQuickActions"),
  statusBar: document.getElementById("statusBar"),

  desktopNav: document.getElementById("desktopNav"),
  mobileNavDrawer: document.getElementById("mobileNavDrawer"),
  mobileNavBackdrop: document.getElementById("mobileNavBackdrop"),
  mobileNavBtn: document.getElementById("mobileNavBtn"),
  closeMobileNavBtn: document.getElementById("closeMobileNavBtn"),
  mobileNavContent: document.getElementById("mobileNavContent"),

  viewContent: document.getElementById("viewContent"),
  mobileBottomBar: document.getElementById("mobileBottomBar"),

  assistantContext: document.getElementById("assistantContext"),
  assistantSuggestions: document.getElementById("assistantSuggestions"),
  assistantMessages: document.getElementById("assistantMessages"),
  assistantForm: document.getElementById("assistantForm"),
  assistantInput: document.getElementById("assistantInput"),
  assistantSendBtn: document.getElementById("assistantSendBtn"),
  assistantLauncher: document.getElementById("assistantLauncher"),
  assistantExpandBtn: document.getElementById("assistantExpandBtn"),

  assistantModal: document.getElementById("assistantModal"),
  assistantBackdrop: document.getElementById("assistantBackdrop"),
  closeAssistantBtn: document.getElementById("closeAssistantBtn"),
  assistantModalMessages: document.getElementById("assistantModalMessages"),
  assistantModalForm: document.getElementById("assistantModalForm"),
  assistantModalInput: document.getElementById("assistantModalInput"),
  assistantModalSendBtn: document.getElementById("assistantModalSendBtn"),
  assistantClearBtn: document.getElementById("assistantClearBtn"),

  scopeBadge: document.getElementById("scopeBadge"),
  scopeHomeBadge: document.getElementById("scopeHomeBadge"),
  scopeChildBadge: document.getElementById("scopeChildBadge"),
  scopeShiftBadge: document.getElementById("scopeShiftBadge"),

  modalScopeHomeBadge: document.getElementById("modalScopeHomeBadge"),
  modalScopeChildBadge: document.getElementById("modalScopeChildBadge"),

  assistantScopeSummary: document.getElementById("assistantScopeSummary"),
  assistantActions: document.getElementById("assistantActions"),
  assistantSources: document.getElementById("assistantSources"),
  assistantRuntime: document.getElementById("assistantRuntime"),
  assistantExplainability: document.getElementById("assistantExplainability"),
  assistantModalScopeSummary: document.getElementById("assistantModalScopeSummary"),
  assistantModalSources: document.getElementById("assistantModalSources"),

  fullscreenPanel: document.getElementById("fullscreenPanel"),
  fullscreenPanelTitle: document.getElementById("fullscreenPanelTitle"),
  fullscreenPanelSubtitle: document.getElementById("fullscreenPanelSubtitle"),
  fullscreenPanelActions: document.getElementById("fullscreenPanelActions"),
  fullscreenPanelBody: document.getElementById("fullscreenPanelBody"),
  closeFullscreenPanelBtn: document.getElementById("closeFullscreenPanelBtn"),

  composerPanel: document.getElementById("composerPanel"),
  composerTitle: document.getElementById("composerTitle"),
  composerSubtitle: document.getElementById("composerSubtitle"),
  composerFields: document.getElementById("recordComposerFields"),
  composerForm: document.getElementById("recordComposerForm"),
  composerGuidanceText: document.getElementById("composerGuidanceText"),
  composerPrompts: document.getElementById("composerPrompts"),
  composerAiFeedback: document.getElementById("composerAiFeedback"),
  composerAutosaveStatus: document.getElementById("composerAutosaveStatus"),
  closeComposerBtn: document.getElementById("closeComposerBtn"),
  composerSaveDraftBtn: document.getElementById("composerSaveDraftBtn"),
  composerCheckBtn: document.getElementById("composerCheckBtn"),
  composerSubmitBtn: document.getElementById("composerSubmitBtn"),
  composerGrammarBtn: document.getElementById("composerGrammarBtn"),
  composerClarityBtn: document.getElementById("composerClarityBtn"),
  composerSafeguardingBtn: document.getElementById("composerSafeguardingBtn"),
  composerChildVoiceBtn: document.getElementById("composerChildVoiceBtn"),

  drawer: document.getElementById("recordDrawer"),
  drawerBackdrop: document.getElementById("recordDrawerBackdrop"),
  drawerTitle: document.getElementById("recordDrawerTitle"),
  drawerSubtitle: document.getElementById("recordDrawerSubtitle"),
  drawerBody: document.getElementById("recordDrawerBody"),
  drawerActions: document.getElementById("recordDrawerActions"),
  closeDrawerBtn: document.getElementById("closeRecordDrawerBtn"),
  drawerEditBtn: document.getElementById("drawerEditBtn"),
  drawerSubmitBtn: document.getElementById("drawerSubmitBtn"),
  drawerApproveBtn: document.getElementById("drawerApproveBtn"),
  drawerReturnBtn: document.getElementById("drawerReturnBtn"),
  drawerArchiveBtn: document.getElementById("drawerArchiveBtn"),

  changePersonBtn: document.getElementById("changePersonBtn"),
};
