from __future__ import annotations

from auth.orb_residential_dependencies import orb_residential_premium_dependency

require_orb_dictate_access = orb_residential_premium_dependency("record_this_properly")
