import { els } from "../dom.js";
import { state } from "../state.js";
import { apiGet } from "../core/api.js";
import { escapeHtml } from "../core/utils.js";
import { listRecords } from "../core/api-adapter.js";
import {
  normaliseRecords,
  sortNormalisedRecordsNewestFirst,
} from "../core/record-normaliser.js";
import { updateWorkspaceSummaryStrip } from "../ui/workspace-summary.js";
import { openRecordDetail } from "../ui/records.js";

function getCurrentScope() {
  return state.currentScope || "child";
}

function getHomeId() {
  const toSafeHomeId = (value) => {
    const parsed = Number(value);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
  };

  const preferredHomeId = toSafeHomeId(
    state.readinessSelectedHomeId ||
      state.homeId ||
      state.selectedHomeId ||
      state.currentHomeId ||
      state.currentUser?.home_id ||
      state.currentUser?.homeId ||
      state.selectedYoungPerson?.home_id ||
      null
  );

  const allowedHomeIds = Array.isArray(state.allowedHomeIds)
    ? state.allowedHomeIds
        .map((item) => Number(item))
        .filter((item) => Number.isFinite(item) && item > 0)
    : [];

  if (allowedHomeIds.length) {
    if (preferredHomeId && allowedHomeIds.includes(preferredHomeId)) {
      return preferredHomeId;
    }
    return allowedHomeIds[0];
  }

  return preferredHomeId;
}

function getYoungPersonId() {
  return (
    state.youngPersonId ||
    state.currentYoungPersonId ||
    state.selectedYoungPerson?.id ||
    state.selectedYoungPerson?.young_person_id ||
    null
  );
}

function getScopeEntityId() {
  return getCurrentScope() === "child" ? getYoungPersonId() : getHomeId();
}

function getScopeTitle() {
  const scope = getCurrentScope();

  if (scope === "home") {
    return (
      state.currentUser?.home_name ||
      state.currentUser?.homeName ||
      (getHomeId() ? `Home ${getHomeId()}` : "Home")
    );
  }

  if (scope === "quality") {
    return (
      state.currentUser?.home_name ||
      state.currentUser?.homeName ||
      (getHomeId() ? `Home ${getHomeId()}` : "Quality and RI")
    );
  }

  const person = state.selectedYoungPerson || state.youngPerson || {};
  return (
    person.full_name ||
    person.name ||
    [person.first_name, person.last_name].filter(Boolean).join(" ").trim() ||
    person.preferred_name ||
    "Young person"
  );
}

function toText(value, fallback = "") {
  return escapeHtml(String(value ?? fallback ?? ""));
}

function formatTimelineDate(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);

  return date.toLocaleString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function getRecordDate(item = {}) {
  return item.date || item.created_at || item.updated_at || null;
}

function getRowTitle(item = {}) {
  return item.title || item.label || "Timeline item";
}

function getRowSummary(item = {}) {
  return item.summary || "No additional summary recorded.";
}

function getRowPill(item = {}) {
  const severity = String(item.severity || "").toLowerCase();
  const status = String(item.status || "").toLowerCase();

  if (
    ["critical", "high"].includes(severity) ||
    ["overdue", "escalated", "returned", "rejected"].includes(status) ||
    item.is_overdue
  ) {
    return { label: "Needs review", tone: "warning" };
  }

  if (["completed", "approved", "complete"].includes(status)) {
    return { label: "Completed", tone: "success" };
  }

  if (["submitted", "pending_review", "draft", "active"].includes(status)) {
    return { label: status.replaceAll("_", " "), tone: "muted" };
  }

  return { label: "Recorded", tone: "muted" };
}

function buildPatternCounts(records = []) {
  const highRisk = records.filter((item) =>
    ["high", "critical"].includes(String(item.severity || "").toLowerCase())
  ).length;

  const safeguarding = records.filter((item) =>
    ["safeguarding_record", "missing_episode", "incident", "risk"].includes(
      String(item.type || item.record_type || "").toLowerCase()
    )
  ).length;

  const childVoice = records.filter((item) => {
    const raw = item.raw || {};
    return Boolean(
      raw.child_voice ||
        raw.young_person_voice ||
        raw.child_voice_present ||
        raw.voice_of_child
    );
  }).length;

  const autoGenerated = records.filter((item) => {
    const raw = item.raw || {};
    return Boolean(raw.auto_generated || raw.generated_by_ai);
  }).length;

  return {
    highRisk,
    safeguarding,
    childVoice,
    autoGenerated,
  };
}

function buildRecentImportantRows(records = []) {
  return records.filter((item) => {
    const severity = String(item.severity || "").toLowerCase();
    const status = String(item.status || "").toLowerCase();
    const type = String(item.type || item.record_type || "").toLowerCase();

    return (
      ["high", "critical"].includes(severity) ||
      ["overdue", "escalated", "returned", "rejected"].includes(status) ||
      ["safeguarding_record", "missing_episode", "incident", "risk"].includes(type) ||
      item.is_overdue
    );
  });
}

function buildCategoryBuckets(records = []) {
  const incidents = records.filter((item) =>
    ["incident", "missing_episode", "safeguarding_record", "risk"].includes(
      String(item.type || item.record_type || "").toLowerCase()
    )
  );

  const health = records.filter((item) =>
    ["health_record", "appointment", "medication_record"].includes(
      String(item.type || item.record_type || "").toLowerCase()
    )
  );

  const education = records.filter((item) =>
    String(item.type || item.record_type || "").toLowerCase().includes("education")
  );

  const family = records.filter((item) =>
    String(item.type || item.record_type || "").toLowerCase().includes("family")
  );

  return { incidents, health, education, family };
}

function buildTopCounts({ timelineRows = [] }) {
  return {
    chronologyItems: timelineRows.length,
    incidents: timelineRows.filter((item) => item.type === "incident").length,
    health: timelineRows.filter((item) =>
      ["health_record", "appointment", "medication_record"].includes(item.type)
    ).length,
    education: timelineRows.filter((item) => item.type === "education_record").length,
  };
}

function renderRecordRows(items = [], emptyMessage = "No timeline items found.") {
  if (!items.length) {
    return `
      <div class="empty-state">
        <p>${toText(emptyMessage)}</p>
      </div>
    `;
  }

  return `
    <div class="record-list">
      ${items
        .map((item) => {
          const pill = getRowPill(item);
          const id = item.id ?? "";
          const type = item.type || item.record_type || "";

          return `
            <article
              class="record-row"
              data-open-record="true"
              data-record-id="${toText(id)}"
              data-record-type="${toText(type)}"
              role="button"
              tabindex="0"
            >
              <div class="record-row-main">
                <div class="record-row-title">${toText(getRowTitle(item))}</div>
                <div class="record-row-summary">${toText(getRowSummary(item))}</div>
                <div class="record-row-meta">${toText(formatTimelineDate(getRecordDate(item)))}</div>
              </div>
              <div class="record-row-side">
                <span class="row-pill ${toText(pill.tone)}">${toText(pill.label)}</span>
              </div>
            </article>
          `;
        })
        .join("")}
    </div>
  `;
}

function renderPriorityList(items = [], emptyMessage = "No recent high-priority events found.") {
  if (!items.length) {
    return `
      <div class="empty-state">
        <p>${toText(emptyMessage)}</p>
      </div>
    `;
  }

  return `
    <div class="priority-list">
      ${items
        .slice(0, 4)
        .map(
          (item) => `
            <article class="priority-item">
              <strong>${toText(getRowTitle(item))}</strong>
              <p>${toText(getRowSummary(item))}</p>
            </article>
          `
        )
        .join("")}
    </div>
  `;
}

function renderTimelineHtml({
  chronology = [],
  timelineRows = [],
  importantRows = [],
  buckets,
  patternCounts,
  topCounts,
}) {
  const scope = getCurrentScope();
  const title =
    scope === "child"
      ? "Timeline overview"
      : scope === "home"
      ? "Home timeline overview"
      : "Quality timeline overview";

  const subtitle = chronology.length
    ? "Chronology and linked records across the current scope."
    : "This view is showing a fallback timeline from linked records.";

  return `
    <section class="overview-panel">
      <div class="overview-panel-head">
        <div>
          <div class="eyebrow">Timeline</div>
          <h2>${toText(title)} • ${toText(getScopeTitle())}</h2>
          <p>${toText(subtitle)}</p>
        </div>
      </div>

      <div class="overview-grid">
        <section class="overview-main">
          <div class="overview-stats-grid">
            <article class="overview-stat-card">
              <span class="overview-stat-label">Timeline items</span>
              <strong class="overview-stat-value">${toText(topCounts.chronologyItems)}</strong>
              <span class="overview-stat-note">Normalised records available</span>
            </article>

            <article class="overview-stat-card">
              <span class="overview-stat-label">Incidents</span>
              <strong class="overview-stat-value">${toText(topCounts.incidents)}</strong>
              <span class="overview-stat-note">Incident-linked records</span>
            </article>

            <article class="overview-stat-card">
              <span class="overview-stat-label">Health</span>
              <strong class="overview-stat-value">${toText(topCounts.health)}</strong>
              <span class="overview-stat-note">Health-related items</span>
            </article>

            <article class="overview-stat-card">
              <span class="overview-stat-label">Education</span>
              <strong class="overview-stat-value">${toText(topCounts.education)}</strong>
              <span class="overview-stat-note">Education-related items</span>
            </article>
          </div>

          <div class="overview-section-card">
            <div class="overview-section-head">
              <h3>Timeline patterns</h3>
              <p>A quick picture of risk, safeguarding and how the timeline has been built.</p>
            </div>

            <div class="record-list">
              <article class="record-row">
                <div class="record-row-main">
                  <div class="record-row-title">High-risk events</div>
                  <div class="record-row-summary">Records marked high or critical.</div>
                </div>
                <div class="record-row-side">
                  <span class="row-pill ${patternCounts.highRisk > 0 ? "warning" : "muted"}">${toText(patternCounts.highRisk)}</span>
                </div>
              </article>

              <article class="record-row">
                <div class="record-row-main">
                  <div class="record-row-title">Safeguarding-linked</div>
                  <div class="record-row-summary">Safeguarding, missing, risk and incident-linked records.</div>
                </div>
                <div class="record-row-side">
                  <span class="row-pill ${patternCounts.safeguarding > 0 ? "warning" : "muted"}">${toText(patternCounts.safeguarding)}</span>
                </div>
              </article>

              <article class="record-row">
                <div class="record-row-main">
                  <div class="record-row-title">Child voice present</div>
                  <div class="record-row-summary">Records where the young person’s voice appears captured.</div>
                </div>
                <div class="record-row-side">
                  <span class="row-pill muted">${toText(patternCounts.childVoice)}</span>
                </div>
              </article>

              <article class="record-row">
                <div class="record-row-main">
                  <div class="record-row-title">Auto-generated</div>
                  <div class="record-row-summary">Records projected or generated by automation.</div>
                </div>
                <div class="record-row-side">
                  <span class="row-pill muted">${toText(patternCounts.autoGenerated)}</span>
                </div>
              </article>
            </div>
          </div>

          <div class="overview-section-card">
            <div class="overview-section-head">
              <h3>Full timeline</h3>
              <p>All available records in newest-first order.</p>
            </div>

            ${renderRecordRows(timelineRows, "No timeline items found.")}
          </div>
        </section>

        <aside class="overview-side">
          <section class="overview-side-card">
            <div class="overview-section-head">
              <h3>Important recent events</h3>
              <p>High-risk, safeguarding-linked or overdue records to notice first.</p>
            </div>

            ${renderPriorityList(importantRows)}
          </section>

          <section class="overview-side-card">
            <div class="overview-section-head">
              <h3>Recent incidents and safeguarding</h3>
              <p>Incident, missing, safeguarding and risk-related items.</p>
            </div>

            ${renderRecordRows(buckets.incidents.slice(0, 8), "No incident-related timeline items found.")}
          </section>

          <section class="overview-side-card">
            <div class="overview-section-head">
              <h3>Recent health-related events</h3>
              <p>Appointments, health records and medication items.</p>
            </div>

            ${renderRecordRows(buckets.health.slice(0, 8), "No health-related timeline items found.")}
          </section>

          <section class="overview-side-card">
            <div class="overview-section-head">
              <h3>Recent education-related events</h3>
              <p>Education records and learning-related items.</p>
            </div>

            ${renderRecordRows(buckets.education.slice(0, 8), "No education-related timeline items found.")}
          </section>

          <section class="overview-side-card">
            <div class="overview-section-head">
              <h3>Recent family-related events</h3>
              <p>Family contact and relationship-related items.</p>
            </div>

            ${renderRecordRows(buckets.family.slice(0, 8), "No family-related timeline items found.")}
          </section>
        </aside>
      </div>
    </section>
  `;
}

function renderNoContext() {
  if (!els.viewContent) return;

  const message =
    getCurrentScope() === "child"
      ? "Select a young person before opening timeline."
      : "A home context is needed before timeline can load.";

  els.viewContent.innerHTML = `
    <div class="empty-state">
      <p>${toText(message)}</p>
    </div>
  `;

  updateWorkspaceSummaryStrip({
    today: "No timeline context",
    nextEvent: "No event loaded",
    lastRecord: "No timeline data",
    openActions: "No actions loaded",
  });
}

async function safeList(recordType, ids = {}) {
  try {
    return await listRecords(recordType, ids);
  } catch (error) {
    console.warn(`[timeline] failed to load ${recordType}`, error);
    return [];
  }
}

async function safeGetRows(url = "") {
  try {
    const response = await apiGet(url, { skipCache: true });

    if (Array.isArray(response)) return response;
    if (Array.isArray(response.items)) return response.items;
    if (Array.isArray(response.records)) return response.records;
    if (Array.isArray(response.results)) return response.results;
    if (Array.isArray(response.data)) return response.data;

    return [];
  } catch (error) {
    console.warn(`[timeline] failed to load ${url}`, error);
    return [];
  }
}

async function loadChildTimeline(youngPersonId) {
  const ids = { youngPersonId };

  const [
    chronology,
    incidents,
    dailyNotes,
    healthRecords,
    educationRecords,
    familyRecords,
    appointments,
    missingEpisodes,
    safeguardingRecords,
    tasks,
    documents,
    statutoryDocuments,
    medicationRecords,
    handoverRecords,
    riskRecords,
    keyworkRecords,
  ] = await Promise.all([
    safeList("chronology_event", ids),
    safeList("incident", ids),
    safeList("daily_note", ids),
    safeList("health_record", ids),
    safeList("education_record", ids),
    safeList("family_contact", ids),
    safeList("appointment", ids),
    safeList("missing_episode", ids),
    safeList("safeguarding_record", ids),
    safeList("task", ids),
    safeList("document", ids),
    safeList("statutory_document", ids),
    safeList("medication_record", ids),
    safeList("handover_record", ids),
    safeList("risk", ids),
    safeList("keywork", ids),
  ]);

  const fallback = [
    ...incidents,
    ...dailyNotes,
    ...healthRecords,
    ...educationRecords,
    ...familyRecords,
    ...appointments,
    ...missingEpisodes,
    ...safeguardingRecords,
    ...tasks,
    ...documents,
    ...statutoryDocuments,
    ...medicationRecords,
    ...handoverRecords,
    ...riskRecords,
    ...keyworkRecords,
  ];

  const timelineRows = sortNormalisedRecordsNewestFirst(
    chronology.length ? chronology : fallback
  );

  return {
    chronology,
    timelineRows,
  };
}

async function loadHomeTimeline(homeId) {
  const urls = [
    `/homes/${homeId}/inspection-scores`,
    `/homes/${homeId}/quality-audits`,
    `/homes/${homeId}/quality-audit-findings`,
    `/homes/${homeId}/quality-audit-actions`,
    `/homes/${homeId}/compliance-items`,
    `/homes/${homeId}/reg44-visits`,
    `/homes/${homeId}/reg44-findings`,
    `/homes/${homeId}/reg44-actions`,
    `/homes/${homeId}/reg45-reviews`,
    `/homes/${homeId}/reg45-actions`,
    `/homes/${homeId}/inspection-section-scores`,
    `/homes/${homeId}/inspection-score-reasons`,
    `/homes/${homeId}/inspection-lines-of-enquiry`,
    `/homes/${homeId}/inspection-improvement-actions`,
    `/homes/${homeId}/manager-review-queue`,
    `/homes/${homeId}/team`,
    `/homes/${homeId}/supervisions`,
    `/homes/${homeId}/training`,
    `/homes/${homeId}/tasks`,
    `/homes/${homeId}/documents`,
    `/homes/${homeId}/reports`,
    `/homes/${homeId}/incidents`,
    `/homes/${homeId}/safeguarding`,
  ];

  const groups = await Promise.all(urls.map(safeGetRows));

  const rows = groups
    .flat()
    .map((row) => ({
      ...row,
      home_id: row.home_id || homeId,
    }));

  const timelineRows = sortNormalisedRecordsNewestFirst(normaliseRecords(rows));

  return {
    chronology: [],
    timelineRows,
  };
}

function bindTimelineRowEvents(records = []) {
  if (!els.viewContent) return;

  const byKey = new Map();

  records.forEach((record) => {
    const key = `${record.type || record.record_type || ""}:${record.id || ""}`;
    byKey.set(key, record);
  });

  els.viewContent.querySelectorAll("[data-open-record='true']").forEach((row) => {
    const open = () => {
      const type = row.getAttribute("data-record-type") || "";
      const id = row.getAttribute("data-record-id") || "";
      const record = byKey.get(`${type}:${id}`);

      if (record) {
        openRecordDetail(record);
      }
    };

    row.addEventListener("click", open);
    row.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        open();
      }
    });
  });
}

export async function loadTimeline() {
  if (!els.viewContent) return;

  const scope = getCurrentScope();
  const id = getScopeEntityId();

  if (!id) {
    renderNoContext();
    return;
  }

  els.viewContent.innerHTML = `
    <div class="loading-state">
      <div>
        <div class="spinner"></div>
        <p>Loading timeline...</p>
      </div>
    </div>
  `;

  try {
    const result =
      scope === "child" ? await loadChildTimeline(id) : await loadHomeTimeline(id);

    const timelineRows = sortNormalisedRecordsNewestFirst(
      normaliseRecords(result.timelineRows)
    );

    const chronology = sortNormalisedRecordsNewestFirst(
      normaliseRecords(result.chronology)
    );

    const importantRows = buildRecentImportantRows(timelineRows).slice(0, 10);
    const buckets = buildCategoryBuckets(timelineRows);
    const patternCounts = buildPatternCounts(timelineRows);
    const topCounts = buildTopCounts({ timelineRows });

    els.viewContent.innerHTML = renderTimelineHtml({
      chronology,
      timelineRows,
      importantRows,
      buckets,
      patternCounts,
      topCounts,
    });

    bindTimelineRowEvents(timelineRows);

    const latest = timelineRows[0] || null;
    const nextAttention = importantRows[0] || null;

    updateWorkspaceSummaryStrip({
      today: `${timelineRows.length} timeline item${timelineRows.length === 1 ? "" : "s"}`,
      nextEvent: nextAttention
        ? `${nextAttention.title || "Priority event"}`
        : "No urgent timeline event",
      lastRecord: latest?.date
        ? `Latest ${formatTimelineDate(latest.date)}`
        : "No recent timeline record",
      openActions: `${importantRows.length} important event${
        importantRows.length === 1 ? "" : "s"
      }`,
    });
  } catch (error) {
    els.viewContent.innerHTML = `
      <div class="empty-state">
        <p>${escapeHtml(error.message || "Failed to load timeline.")}</p>
      </div>
    `;

    updateWorkspaceSummaryStrip({
      today: "Timeline unavailable",
      nextEvent: "Unable to load",
      lastRecord: "No timeline data",
      openActions: "Check API routes",
    });
  }
}

export const loadCurrentView = loadTimeline;
