import Link from 'next/link'

import { ReportPreview } from '@/components/indicare/report-preview'
import { Card, DataTable, EmptyState, PageHeader, SectionHeader, StatCard, StatusBadge } from '@/components/indicare/ui'
import { indicareData } from '@/lib/indicare/demo-data'
import { buildOfstedEvidenceOutline, buildWeeklyCareSummary } from '@/lib/indicare/reports'
import { fullName, getStaffById, getYoungPersonById } from '@/lib/indicare/selectors'

const reportTypes = [
  'Weekly care summary',
  'Monthly placement report',
  'Incident summary',
  'Risk review',
  'Safeguarding chronology',
  'Keywork summary',
  'Education summary',
  'Health summary',
  'Ofsted evidence pack outline'
]

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Reports" title="Report generator" description="Structured report foundations that gather relevant daily logs, incidents, risks, keywork, medication, safeguarding, appointments, documents and staff notes." action={<Link href="/assistant" className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-500/30">Assistant draft</Link>} />
      <section className="grid gap-4 md:grid-cols-4">
        <StatCard label="Report types" value={reportTypes.length} />
        <StatCard label="Drafts" value={indicareData.reports.filter((report) => report.status === 'draft').length} />
        <StatCard label="Review" value={indicareData.reports.filter((report) => report.status === 'review').length} />
        <StatCard label="Overdue" value={indicareData.reports.filter((report) => report.status === 'overdue').length} />
      </section>
      <Card>
        <SectionHeader eyebrow="Types" title="Available report foundations" />
        <div className="grid gap-3 md:grid-cols-3">
          {reportTypes.map((type) => <div key={type} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4 text-sm font-black text-slate-700">{type}</div>)}
        </div>
      </Card>
      <Card>
        <SectionHeader eyebrow="Register" title="Generated and draft reports" />
        <DataTable
          headers={['Title', 'Type', 'Young person', 'Date range', 'Generated by', 'Status', 'Actions']}
          rows={indicareData.reports.map((report) => {
            const person = getYoungPersonById(report.youngPersonId)
            const staff = getStaffById(report.generatedBy)
            return [
              <Link key={report.id} href={`/reports/${report.id}`} className="font-black text-slate-950 hover:text-blue-700">{report.title}</Link>,
              report.type,
              person ? fullName(person) : report.youngPersonId,
              `${report.dateRangeStart} to ${report.dateRangeEnd}`,
              staff ? fullName(staff) : report.generatedBy,
              <StatusBadge key="status" value={report.status} />,
              <Link key="action" href={`/reports/${report.id}`} className="font-bold text-blue-700">Open draft</Link>
            ]
          })}
          empty={<EmptyState title="No reports generated" description="No reports have been generated yet." />}
        />
      </Card>
      <section className="grid gap-6 xl:grid-cols-2">
        <Card>
          <SectionHeader eyebrow="Preview" title="Weekly care summary sections" />
          <ReportPreview sections={buildWeeklyCareSummary('yp-jamie').slice(0, 4)} />
        </Card>
        <Card>
          <SectionHeader eyebrow="Inspection" title="Ofsted evidence outline" />
          <ReportPreview sections={buildOfstedEvidenceOutline('yp-noah').slice(0, 5)} />
        </Card>
      </section>
    </div>
  )
}
