import Link from 'next/link'

import { LiveDataStatus } from '@/components/indicare/live-data-status'
import { CognitionPromptStack, OperationalSignalGrid } from '@/components/indicare/operational-cognition-widgets'
import { Card, DataTable, EmptyState, PageHeader, SectionHeader, StatCard, StatusBadge } from '@/components/indicare/ui'
import { getOsReports } from '@/lib/os-api/reports'
import { reportTemplates } from '@/lib/regulatory-reporting/templates'

export default async function ReportsPage() {
  const reportsResult = await getOsReports()
  const reports = reportsResult.data
  const reviewReports = reports.filter((report) => report.status.includes('review'))
  const citedReports = reports.filter((report) => report.citations.length)

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reports"
        title="Regulatory and care report generator"
        description="Draft report foundations that gather chronology events, evidence, actions and citations. All generated text is draft and review required."
        action={<Link href="/chronology" className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-500/30">Open chronology</Link>}
      />
      <LiveDataStatus result={reportsResult} />
      <section className="grid gap-4 md:grid-cols-4">
        <StatCard label="Report templates" value={reportTemplates.length} />
        <StatCard label="Drafts" value={reports.filter((report) => report.status === 'draft').length} />
        <StatCard label="Review" value={reports.filter((report) => report.status.includes('review')).length} />
        <StatCard label="Citations linked" value={reports.reduce((total, report) => total + report.citations.length, 0)} />
      </section>
      <OperationalSignalGrid
        signals={[
          { label: 'Evidence quality', value: citedReports.length, detail: 'Reports with citations attached', tone: 'blue' },
          { label: 'Review posture', value: reviewReports.length, detail: 'Drafts requiring professional review', tone: reviewReports.length ? 'amber' : 'emerald' },
          { label: 'SCCIF readiness', value: reportTemplates.length, detail: 'Available regulatory and care templates', tone: 'purple' },
          { label: 'Child voice', value: reports.filter((report) => /child voice|wishes|feelings/i.test(`${report.title} ${report.body || ''}`)).length, detail: 'Visible child voice markers in report metadata', tone: 'emerald' }
        ]}
      />
      <CognitionPromptStack
        title="Report review prompts"
        prompts={[
          'What evidence would help this report read as the child’s lived journey rather than a compliance summary?',
          'Which citations are strongest for SCCIF leadership, protection and progress?',
          'Where does the report need clearer child voice, family context or relationship impact?',
          'What manager review should happen before this report is relied on externally?'
        ]}
        action={<Link href="/orb?scope=inspection" className="rounded-2xl bg-white px-4 py-3 text-sm font-black text-slate-950">Ask ORB</Link>}
      />
      <Card>
        <SectionHeader eyebrow="Register" title="Generated and draft reports" />
        <DataTable
          headers={['Title', 'Type', 'Young person', 'Date range', 'Generated by', 'Status', 'Actions']}
          rows={reports.map((report) => [
              <Link key={report.id} href={`/reports/${report.id}`} className="font-black text-slate-950 hover:text-blue-700">{report.title}</Link>,
              report.type,
              report.youngPersonId || 'Home-wide',
              `${report.dateRangeStart || 'Open'} to ${report.dateRangeEnd || 'Open'}`,
              report.generatedBy || 'Not recorded',
              <StatusBadge key="status" value={report.status} />,
              <Link key="action" href={`/reports/${report.id}`} className="font-bold text-blue-700">Open draft</Link>
          ])}
          empty={<EmptyState title="No reports generated" description="No reports have been generated yet." />}
        />
      </Card>
    </div>
  )
}
