"""ORB Brain Route Convergence Audit — machine-readable route matrix.

Mapping-only audit artefact for Phase 1 convergence review. Does not route
traffic or change behaviour. See docs/audits/orb-brain-route-convergence-audit.md.
"""

from __future__ import annotations

from typing import Any, Literal

Recommendation = Literal[
    "keep_as_is",
    "converge_soon",
    "add_context",
    "add_tests",
    "retire",
    "phase_2d_safety",
]
Phase = Literal["1_audit", "2_converge", "2d_safety", "3_retire", "none"]
ActiveStatus = Literal["active", "legacy", "compatibility", "retired", "unmounted", "dormant"]

# Columns: route, module, active_status, product_surface, access_control,
# current_brain_orchestrator, context_passed, intent_classification, safety_layer,
# retrieval_rag, governed_egress, risk_level, recommendation, suggested_phase
ROUTE_CONVERGENCE_MATRIX: list[dict[str, Any]] = [
    # --- Canonical standalone ORB chat ---
    {
        "route": "POST /orb/standalone/conversation",
        "module": "routers/orb_standalone_routes.py",
        "active_status": "active",
        "product_surface": "orb_standalone_chat",
        "access_control": "orb_residential / authenticated standalone",
        "current_brain_orchestrator": "orb_brain_convergence_orchestrator_service → orb_converged_general_assistant_service → orb_general_assistant_service",
        "context_passed": "user, mode, source_surface, client_route_hint, location_hint, requested_action, note_type, profile/doc/history; no live OS child/home",
        "intent_classification": True,
        "safety_layer": "orb_safety_scaffold, mandatory contracts, residential finalization, plan enforcement",
        "retrieval_rag": "orb_knowledge_retrieval_service.prepare_request_bundle + shared_institutional_cognition_runtime",
        "governed_egress": "ai_model_router_service (FEATURE_ORB_MODEL_ROUTER_CHAT)",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/standalone/conversation/stream",
        "module": "routers/orb_standalone_routes.py",
        "active_status": "active",
        "product_surface": "orb_standalone_chat_stream",
        "access_control": "orb_residential / authenticated standalone",
        "current_brain_orchestrator": "Same as sync conversation via _build_standalone_request_context",
        "context_passed": "Same as sync conversation",
        "intent_classification": True,
        "safety_layer": "Same as sync + stream status / instant lines",
        "retrieval_rag": "Same as sync (skipped on fast tier)",
        "governed_egress": "ai_model_router_service stream_with_routing",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/standalone/brain-route",
        "module": "routers/orb_standalone_routes.py",
        "active_status": "active",
        "product_surface": "orb_standalone_brain_preview",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_brain_convergence_orchestrator_service.build_brain_decision (metadata only)",
        "context_passed": "message, mode, route hints",
        "intent_classification": True,
        "safety_layer": "contracts/boundaries in metadata; sanitised preview",
        "retrieval_rag": "route map trace only",
        "governed_egress": "none",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/standalone/actions/run",
        "module": "routers/orb_standalone_routes.py",
        "active_status": "active",
        "product_surface": "orb_standalone_actions",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_action_engine_service.run_action → build_brain_decision",
        "context_passed": "action id, message, mode, source_answer",
        "intent_classification": True,
        "safety_layer": "action engine guardrails + finalize_standalone_intelligence",
        "retrieval_rag": "action-specific retrieval",
        "governed_egress": "ai_model_router via action engine",
        "risk_level": "medium",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    # --- ORB Residential premium alias ---
    {
        "route": "POST /orb/residential/conversation",
        "module": "routers/orb_residential_premium_routes.py",
        "active_status": "active",
        "product_surface": "orb_residential_premium",
        "access_control": "orb_residential tier",
        "current_brain_orchestrator": "orb_converged_general_assistant_service → finalize_orb_residential_answer",
        "context_passed": "message, mode, detail, history, optional document",
        "intent_classification": True,
        "safety_layer": "residential finalization",
        "retrieval_rag": "orb_knowledge_retrieval_service",
        "governed_egress": "ai_model_router_service",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    # --- Dictate / Write (write lives under dictate) ---
    {
        "route": "POST /orb/dictate/generate",
        "module": "routers/orb_dictate_routes.py",
        "active_status": "active",
        "product_surface": "orb_dictate",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_unified_brain_gateway.generate_dictate_draft → orb_document_brain_adapter_service → build_brain_decision",
        "context_passed": "note_type, transcript, mode; user/home/provider from auth",
        "intent_classification": True,
        "safety_layer": "redaction, mandatory contracts, residential finalization",
        "retrieval_rag": "knowledge vaults from convergence metadata",
        "governed_egress": "try_governed_draft_text (FEATURE_DICTATE, CONFIDENTIAL_CHILD)",
        "risk_level": "medium",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/dictate/finalise",
        "module": "routers/orb_dictate_routes.py",
        "active_status": "active",
        "product_surface": "orb_dictate",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_dictate_service → orb_unified_brain_gateway",
        "context_passed": "note_type, session payload",
        "intent_classification": True,
        "safety_layer": "same as generate",
        "retrieval_rag": "convergence metadata vaults",
        "governed_egress": "try_governed_draft_text (FEATURE_DICTATE)",
        "risk_level": "medium",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/dictate/edit",
        "module": "routers/orb_dictate_routes.py",
        "active_status": "active",
        "product_surface": "orb_dictate_edit",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_unified_brain_gateway.edit_dictate_draft",
        "context_passed": "document text, note_type",
        "intent_classification": True,
        "safety_layer": "mandatory contracts, finalization",
        "retrieval_rag": "contract blocks",
        "governed_egress": "try_governed_draft_text (FEATURE_DICTATE_EDIT)",
        "risk_level": "medium",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/dictate/prepare-write",
        "module": "routers/orb_dictate_routes.py",
        "active_status": "active",
        "product_surface": "orb_write",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_unified_brain_gateway.build_write_brain_context (metadata only)",
        "context_passed": "note_type, source text",
        "intent_classification": True,
        "safety_layer": "standalone boundary",
        "retrieval_rag": "none (metadata only)",
        "governed_egress": "none",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/dictate/realtime/session",
        "module": "routers/orb_dictate_routes.py",
        "active_status": "active",
        "product_surface": "orb_dictate_realtime",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "issue_orb_dictate_transcription_realtime_session (transport only)",
        "context_passed": "user",
        "intent_classification": False,
        "safety_layer": "realtime governance service (PR #1793)",
        "retrieval_rag": "none",
        "governed_egress": "FEATURE_ORB_DICTATE_REALTIME_SESSION",
        "risk_level": "medium",
        "recommendation": "add_tests",
        "suggested_phase": "none",
    },
    # --- Voice ---
    {
        "route": "POST /orb/voice/respond",
        "module": "routers/orb_voice_residential_routes.py",
        "active_status": "active",
        "product_surface": "orb_voice",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_voice_brain_router_service.classify_voice_intent → orb_voice_respond_service (tiered)",
        "context_passed": "mode, transcript, session memory/turns; user/provider",
        "intent_classification": True,
        "safety_layer": "safety scaffold, protocol blocks, recording contract snippets",
        "retrieval_rag": "policy phrase retrieval on specialist paths",
        "governed_egress": "governed_draft_text (FEATURE_VOICE_RESPOND); voice_fast skips convergence",
        "risk_level": "medium",
        "recommendation": "add_context",
        "suggested_phase": "2_converge",
        "notes": "voice_fast tier skips convergence orchestrator; specialist/safeguarding uses it",
    },
    {
        "route": "POST /orb/voice/v2/respond",
        "module": "routers/orb_voice_v2_routes.py",
        "active_status": "active",
        "product_surface": "orb_voice_v2",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_voice_v2_service → generate_voice_response (same tiered model)",
        "context_passed": "same as voice/respond + personality",
        "intent_classification": True,
        "safety_layer": "same as voice/respond",
        "retrieval_rag": "same as voice/respond",
        "governed_egress": "governed_draft_text (FEATURE_VOICE_RESPOND)",
        "risk_level": "medium",
        "recommendation": "add_context",
        "suggested_phase": "2_converge",
    },
    {
        "route": "WS /orb/voice/ws/{session_id}",
        "module": "routers/orb_voice_residential_routes.py",
        "active_status": "active",
        "product_surface": "orb_voice_realtime",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_voice_realtime_ws_handler (provider realtime; no full convergence in-session)",
        "context_passed": "session",
        "intent_classification": False,
        "safety_layer": "realtime governance at session issue (PR #1792)",
        "retrieval_rag": "none in-session",
        "governed_egress": "FEATURE_ORB_REALTIME_VOICE_SESSION",
        "risk_level": "high",
        "recommendation": "phase_2d_safety",
        "suggested_phase": "2d_safety",
        "notes": "Raw provider text in-session; mitigated by handoff to Dictate/Chat",
    },
    {
        "route": "POST /orb/voice/realtime/session",
        "module": "routers/orb_voice_residential_routes.py",
        "active_status": "active",
        "product_surface": "orb_voice_realtime",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "issue_orb_voice_conversational_realtime_session",
        "context_passed": "voice profile, mode",
        "intent_classification": False,
        "safety_layer": "realtime governance (PR #1792)",
        "retrieval_rag": "none",
        "governed_egress": "FEATURE_ORB_REALTIME_VOICE_SESSION",
        "risk_level": "medium",
        "recommendation": "add_tests",
        "suggested_phase": "none",
    },
    # --- Communicate ---
    {
        "route": "POST /orb/communicate/converge",
        "module": "routers/orb_communicate_routes.py",
        "active_status": "active",
        "product_surface": "orb_communicate",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "build_brain_decision (metadata only; no LLM)",
        "context_passed": "text, mode, workflow",
        "intent_classification": True,
        "safety_layer": "boundaries in metadata",
        "retrieval_rag": "source-family chips (non-live)",
        "governed_egress": "none",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/communicate/support-pack",
        "module": "routers/orb_communicate_routes.py",
        "active_status": "active",
        "product_surface": "orb_communicate",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_communicate_support_pack_service (deterministic) + orchestrator metadata",
        "context_passed": "situation, audience, communication needs",
        "intent_classification": True,
        "safety_layer": "safeguarding guardrails, strip leading questions",
        "retrieval_rag": "source chips from convergence",
        "governed_egress": "none",
        "risk_level": "low",
        "recommendation": "keep_as_is",
        "suggested_phase": "none",
    },
    # --- Standalone satellites ---
    {
        "route": "POST /orb/standalone/agents/run",
        "module": "routers/orb_agent_routes.py",
        "active_status": "active",
        "product_surface": "orb_agents",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_agent_orchestrator_service (intelligence packet + shared cognition; partial convergence orchestrator)",
        "context_passed": "agent_type, prompt, mode; no OS records",
        "intent_classification": True,
        "safety_layer": "indicare_ai_governance_event_service, quality gate preview",
        "retrieval_rag": "orb_rag_retrieval_service + source packs",
        "governed_egress": "ai_model_router_service",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
        "notes": "Uses intelligence packet but not full build_brain_decision path",
    },
    {
        "route": "POST /orb/standalone/agents/deep-research",
        "module": "routers/orb_agent_routes.py",
        "active_status": "active",
        "product_surface": "orb_agents",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_deep_research_service → orb_agent_orchestrator_service",
        "context_passed": "prompt, mode; multi-pass RAG",
        "intent_classification": True,
        "safety_layer": "governance events, quality gate",
        "retrieval_rag": "multi-pass RAG clustering",
        "governed_egress": "ai_model_router_service",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    {
        "route": "POST /orb/standalone/documents/intelligence",
        "module": "routers/orb_document_routes.py",
        "active_status": "active",
        "product_surface": "orb_documents",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_document_intelligence_service → build_brain_decision metadata",
        "context_passed": "document_text, lens, mode",
        "intent_classification": True,
        "safety_layer": "standalone boundary, brain metadata contract",
        "retrieval_rag": "document understanding (separate from chat retrieval bundle)",
        "governed_egress": "ai_model_router via document services",
        "risk_level": "medium",
        "recommendation": "add_tests",
        "suggested_phase": "none",
    },
    {
        "route": "POST /orb/standalone/templates/{id}/generate",
        "module": "routers/orb_template_routes.py",
        "active_status": "active",
        "product_surface": "orb_templates",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "template generation service + orchestrator metadata on review paths",
        "context_passed": "template id, inputs, mode",
        "intent_classification": True,
        "safety_layer": "template service guardrails",
        "retrieval_rag": "template-specific",
        "governed_egress": "ai_model_router",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    {
        "route": "POST /orb/standalone/shift-builder/generate",
        "module": "routers/orb_shift_builder_routes.py",
        "active_status": "active",
        "product_surface": "orb_shift_builder",
        "access_control": "authenticated standalone",
        "current_brain_orchestrator": "orb_shift_builder_service → action engine (partial convergence)",
        "context_passed": "notes, focus areas",
        "intent_classification": False,
        "safety_layer": "conditional finalization",
        "retrieval_rag": "limited",
        "governed_egress": "ai_model_router",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    # --- OS operational ORB ---
    {
        "route": "POST /assistant/orb/conversation",
        "module": "routers/orb_operational_routes.py",
        "active_status": "active",
        "product_surface": "os_orb",
        "access_control": "permissioned OS roles; child/home/staff scope",
        "current_brain_orchestrator": "orb_operational_assistant_service (standalone brain blocks; not full convergence orchestrator)",
        "context_passed": "scope, child_id, home_id, staff_id, mode; permissioned OS records",
        "intent_classification": True,
        "safety_layer": "finalize_standalone_intelligence, permission bridge, privacy guard",
        "retrieval_rag": "orb_universal_evidence_service + OKR",
        "governed_egress": "ai_model_router operational surface",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
        "notes": "Uses orb_standalone_brain_service blocks but not build_brain_decision",
    },
    {
        "route": "POST /assistant/orb/operational",
        "module": "routers/orb_operational_routes.py",
        "active_status": "active",
        "product_surface": "os_orb_bridge",
        "access_control": "permissioned OS",
        "current_brain_orchestrator": "orb_intelligence_bridge_service",
        "context_passed": "operational scope",
        "intent_classification": True,
        "safety_layer": "audit, permissions",
        "retrieval_rag": "universal evidence",
        "governed_egress": "operational model router",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    # --- Legacy OS-linked /orb ---
    {
        "route": "POST /orb/conversation",
        "module": "routers/orb_routes.py",
        "active_status": "legacy",
        "product_surface": "legacy_os_orb",
        "access_control": "authenticated",
        "current_brain_orchestrator": "orb_general_assistant_service.answer (direct; no convergence/finalization)",
        "context_passed": "message, mode; minimal",
        "intent_classification": False,
        "safety_layer": "basic model router only",
        "retrieval_rag": "legacy retrieval path",
        "governed_egress": "ai_model_router (ungoverned draft path)",
        "risk_level": "high",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
        "notes": "Red in generate_orb_residential_route_map.py; not used by ORB Residential shell",
    },
    {
        "route": "POST /orb/session/start",
        "module": "routers/orb_routes.py",
        "active_status": "legacy",
        "product_surface": "legacy_orb_voice",
        "access_control": "authenticated",
        "current_brain_orchestrator": "session plumbing (governed PR #1795)",
        "context_passed": "session config",
        "intent_classification": False,
        "safety_layer": "realtime governance",
        "retrieval_rag": "none",
        "governed_egress": "FEATURE_ORB_SESSION_START",
        "risk_level": "medium",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
    },
    {
        "route": "POST /orb/realtime/session",
        "module": "routers/orb_routes.py",
        "active_status": "legacy",
        "product_surface": "legacy_orb_realtime",
        "access_control": "authenticated",
        "current_brain_orchestrator": "realtime session issue (governed PR #1794)",
        "context_passed": "session config",
        "intent_classification": False,
        "safety_layer": "realtime governance",
        "retrieval_rag": "none",
        "governed_egress": "FEATURE_ORB_REALTIME_SESSION",
        "risk_level": "medium",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
    },
    {
        "route": "WS /orb/realtime/ws",
        "module": "routers/orb_routes.py",
        "active_status": "legacy",
        "product_surface": "legacy_orb_realtime",
        "access_control": "authenticated",
        "current_brain_orchestrator": "legacy realtime websocket handler",
        "context_passed": "session",
        "intent_classification": False,
        "safety_layer": "partial",
        "retrieval_rag": "none",
        "governed_egress": "legacy realtime path",
        "risk_level": "high",
        "recommendation": "phase_2d_safety",
        "suggested_phase": "2d_safety",
    },
    # --- OS embedded assistants (non-ORB brain) ---
    {
        "route": "POST /assistant/general/stream",
        "module": "routers/assistant_general_routes.py",
        "active_status": "active",
        "product_surface": "indicare_ai_suite",
        "access_control": "authenticated; optional young_person/home/project scope",
        "current_brain_orchestrator": "assistant_general_service → assistant/llm_provider (NOT convergence orchestrator)",
        "context_passed": "user, young_person_id, home_id, project_id, document, ai-suite mode",
        "intent_classification": True,
        "safety_layer": "safeguarding escalation, prompt injection, standalone data boundary",
        "retrieval_rag": "assistant/knowledge_loader official sources; optional IndiCareAIOrchestratorService",
        "governed_egress": "assistant/llm_provider governance metadata (not try_governed_draft_text)",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
        "notes": "Separate AI Suite stack; future convergence candidate",
    },
    {
        "route": "POST /assistant/os/young-people/stream",
        "module": "routers/assistant_os_routes.py",
        "active_status": "active",
        "product_surface": "os_young_people_assistant",
        "access_control": "child access assert; role scope",
        "current_brain_orchestrator": "assistant_orchestrator → ai_service.generate_ai_stream",
        "context_passed": "young_person_id, home, section, reporting period, evidence",
        "intent_classification": True,
        "safety_layer": "role scope, home context, injection guards, evidence grounding",
        "retrieval_rag": "build_runtime_assistant_context + evidence index",
        "governed_egress": "generate_ai_stream → assistant/llm_provider",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
        "notes": "Canonical OS path; does not use ORB convergence orchestrator",
    },
    {
        "route": "POST /assistant/os/home/stream",
        "module": "routers/assistant_os_routes.py",
        "active_status": "active",
        "product_surface": "os_home_assistant",
        "access_control": "home/provider scope",
        "current_brain_orchestrator": "assistant_orchestrator → generate_ai_stream",
        "context_passed": "home_id, provider scope, evidence",
        "intent_classification": True,
        "safety_layer": "same as young-people stream",
        "retrieval_rag": "home evidence retrieval",
        "governed_egress": "generate_ai_stream",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    {
        "route": "POST /assistant/os/quality/stream",
        "module": "routers/assistant_os_routes.py",
        "active_status": "active",
        "product_surface": "os_quality_assistant",
        "access_control": "quality/reg scope",
        "current_brain_orchestrator": "assistant_orchestrator → generate_ai_stream",
        "context_passed": "home/provider quality scope",
        "intent_classification": True,
        "safety_layer": "same as young-people stream",
        "retrieval_rag": "quality/reg evidence",
        "governed_egress": "generate_ai_stream",
        "risk_level": "medium",
        "recommendation": "converge_soon",
        "suggested_phase": "2_converge",
    },
    {
        "route": "POST /assistant-api/young-people/assistant",
        "module": "routers/assistant_routes.py",
        "active_status": "legacy",
        "product_surface": "os_young_people_assistant",
        "access_control": "same as /assistant/os/young-people/stream",
        "current_brain_orchestrator": "assistant_orchestrator → generate_ai_stream (duplicate path)",
        "context_passed": "same as canonical OS stream",
        "intent_classification": True,
        "safety_layer": "same as canonical OS stream",
        "retrieval_rag": "same as canonical OS stream",
        "governed_egress": "generate_ai_stream",
        "risk_level": "medium",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
        "notes": "Legacy duplicate; canonical path is /assistant/os/young-people/stream",
    },
    {
        "route": "POST /assistant-api/home/assistant",
        "module": "routers/assistant_routes.py",
        "active_status": "legacy",
        "product_surface": "os_home_assistant",
        "access_control": "same as /assistant/os/home/stream",
        "current_brain_orchestrator": "assistant_orchestrator → generate_ai_stream (duplicate)",
        "context_passed": "same as canonical OS stream",
        "intent_classification": True,
        "safety_layer": "same as canonical OS stream",
        "retrieval_rag": "same as canonical OS stream",
        "governed_egress": "generate_ai_stream",
        "risk_level": "medium",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
    },
    {
        "route": "POST /assistant-api/quality/assistant",
        "module": "routers/assistant_routes.py",
        "active_status": "legacy",
        "product_surface": "os_quality_assistant",
        "access_control": "same as /assistant/os/quality/stream",
        "current_brain_orchestrator": "assistant_orchestrator → generate_ai_stream (duplicate)",
        "context_passed": "same as canonical OS stream",
        "intent_classification": True,
        "safety_layer": "same as canonical OS stream",
        "retrieval_rag": "same as canonical OS stream",
        "governed_egress": "generate_ai_stream",
        "risk_level": "medium",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
    },
    # --- Unmounted / dormant ---
    {
        "route": "POST /young-people/assistant",
        "module": "routers/young_people_assistant_routes.py",
        "active_status": "unmounted",
        "product_surface": "os_young_people_assistant",
        "access_control": "would mirror assistant-api",
        "current_brain_orchestrator": "generate_ai_stream (if mounted)",
        "context_passed": "young_person scope",
        "intent_classification": True,
        "safety_layer": "assistant_security",
        "retrieval_rag": "evidence index",
        "governed_egress": "generate_ai_stream",
        "risk_level": "high",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
        "notes": "File exists but not in ROUTERS registry",
    },
    {
        "route": "POST /assistant/query",
        "module": "routers/assistant_query_routes.py",
        "active_status": "unmounted",
        "product_surface": "legacy_assistant_query",
        "access_control": "unknown",
        "current_brain_orchestrator": "AssistantResponseService + AssistantRetrievalService",
        "context_passed": "query payload",
        "intent_classification": False,
        "safety_layer": "unknown",
        "retrieval_rag": "AssistantRetrievalService",
        "governed_egress": "legacy assistant path",
        "risk_level": "high",
        "recommendation": "retire",
        "suggested_phase": "3_retire",
    },
    {
        "route": "WS /assistant/realtime/ws",
        "module": "routers/assistant_realtime_proxy_routes.py",
        "active_status": "unmounted",
        "product_surface": "dangerous_realtime_proxy",
        "access_control": "n/a",
        "current_brain_orchestrator": "raw websockets.connect to OpenAI (bypasses governed egress)",
        "context_passed": "none",
        "intent_classification": False,
        "safety_layer": "none",
        "retrieval_rag": "none",
        "governed_egress": "NONE — direct provider bypass",
        "risk_level": "critical",
        "recommendation": "phase_2d_safety",
        "suggested_phase": "2d_safety",
        "notes": "UNMOUNTED_DANGEROUS_ASSISTANT_REALTIME_ROUTERS; guarded by test_assistant_realtime_router_guard",
    },
    {
        "route": "POST /assistant/realtime/session",
        "module": "routers/assistant_realtime_voice_routes.py",
        "active_status": "unmounted",
        "product_surface": "dangerous_realtime_session",
        "access_control": "n/a",
        "current_brain_orchestrator": "orb_realtime_provider_service.create_ephemeral_session (ungoverned)",
        "context_passed": "none",
        "intent_classification": False,
        "safety_layer": "none",
        "retrieval_rag": "none",
        "governed_egress": "NONE — bypasses issue_realtime_session",
        "risk_level": "critical",
        "recommendation": "phase_2d_safety",
        "suggested_phase": "2d_safety",
    },
    {
        "route": "POST /v1/assistant/respond",
        "module": "routers/assistant_partner_api.py",
        "active_status": "unmounted",
        "product_surface": "partner_api",
        "access_control": "partner API key",
        "current_brain_orchestrator": "partner assistant path",
        "context_passed": "partner payload",
        "intent_classification": False,
        "safety_layer": "partner auth",
        "retrieval_rag": "unknown",
        "governed_egress": "unknown",
        "risk_level": "high",
        "recommendation": "phase_2d_safety",
        "suggested_phase": "2d_safety",
    },
]

# Routes that MUST reference the convergence orchestrator in their router module source.
CONVERGED_ROUTE_SOURCE_ASSERTIONS: dict[str, list[str]] = {
    "routers/orb_standalone_routes.py": [
        "orb_brain_convergence_orchestrator_service",
        "build_brain_decision",
    ],
    "services/orb_dictate_service.py": [
        "orb_unified_brain_gateway",
        "generate_dictate_draft",
    ],
    "routers/orb_communicate_routes.py": [
        "orb_brain_convergence_orchestrator_service",
    ],
}

# Routes that must NOT bypass to raw provider adapters.
NO_RAW_PROVIDER_BYPASS_ROUTES: frozenset[str] = frozenset(
    {
        "POST /orb/standalone/conversation",
        "POST /orb/standalone/conversation/stream",
        "POST /orb/dictate/generate",
        "POST /orb/voice/respond",
    }
)

BRAIN_GAPS: list[dict[str, str]] = [
    {
        "gap": "os_assistants_bypass_convergence",
        "routes": "/assistant/os/*, /assistant-api/*, /assistant/general/stream",
        "detail": "OS embedded assistants use assistant_orchestrator + generate_ai_stream, not orb_brain_convergence_orchestrator_service",
    },
    {
        "gap": "legacy_orb_conversation",
        "routes": "POST /orb/conversation",
        "detail": "Direct orb_general_assistant_service without convergence or residential finalization",
    },
    {
        "gap": "voice_fast_skips_convergence",
        "routes": "POST /orb/voice/respond (voice_fast tier)",
        "detail": "Fast voice tier intentionally skips convergence orchestrator for latency",
    },
    {
        "gap": "agents_partial_convergence",
        "routes": "POST /orb/standalone/agents/run",
        "detail": "Uses intelligence packet + shared cognition but not full build_brain_decision",
    },
    {
        "gap": "operational_orb_partial_convergence",
        "routes": "POST /assistant/orb/conversation",
        "detail": "Uses standalone brain blocks but not convergence orchestrator",
    },
    {
        "gap": "duplicate_os_assistant_paths",
        "routes": "/assistant-api/* vs /assistant/os/*/stream",
        "detail": "Same handlers mounted at two path prefixes",
    },
    {
        "gap": "duplicate_retrieval_stacks",
        "routes": "standalone chat vs OS assistants",
        "detail": "orb_knowledge_retrieval_service vs build_runtime_assistant_context evidence index",
    },
    {
        "gap": "realtime_in_session_raw_text",
        "routes": "WS /orb/voice/ws/{session_id}, WS /orb/realtime/ws",
        "detail": "Provider realtime text not passed through residential finalization in-session",
    },
    {
        "gap": "unmounted_dangerous_realtime",
        "routes": "/assistant/realtime/*",
        "detail": "Modules exist with direct provider bypass; guarded unmounted",
    },
]

DUPLICATE_RETRIEVAL_PATHS: list[dict[str, str]] = [
    {
        "path_a": "orb_knowledge_retrieval_service.prepare_request_bundle",
        "path_b": "build_runtime_assistant_context + evidence_index",
        "surfaces": "standalone ORB chat vs OS assistants",
        "recommendation": "Converge retrieval planning in Phase 2; keep separate boundaries (standalone vs OS)",
    },
    {
        "path_a": "orb_rag_retrieval_service (agents)",
        "path_b": "orb_knowledge_retrieval_service (chat)",
        "surfaces": "agent runs vs standalone conversation",
        "recommendation": "Unify RAG entry through convergence metadata in Phase 2",
    },
    {
        "path_a": "assistant/knowledge_loader (general stream)",
        "path_b": "orb_knowledge_retrieval_service",
        "surfaces": "AI Suite vs ORB Residential",
        "recommendation": "Map knowledge modules to convergence vaults",
    },
]


class OrbBrainRouteConvergenceAuditService:
    """Read-only audit helpers for route convergence matrix and gap analysis."""

    def matrix(self) -> list[dict[str, Any]]:
        return list(ROUTE_CONVERGENCE_MATRIX)

    def brain_gaps(self) -> list[dict[str, str]]:
        return list(BRAIN_GAPS)

    def duplicate_retrieval_paths(self) -> list[dict[str, str]]:
        return list(DUPLICATE_RETRIEVAL_PATHS)

    def by_recommendation(self, recommendation: Recommendation) -> list[dict[str, Any]]:
        return [row for row in ROUTE_CONVERGENCE_MATRIX if row["recommendation"] == recommendation]

    def by_active_status(self, status: ActiveStatus) -> list[dict[str, Any]]:
        return [row for row in ROUTE_CONVERGENCE_MATRIX if row["active_status"] == status]

    def converged_routes(self) -> list[str]:
        return [
            row["route"]
            for row in ROUTE_CONVERGENCE_MATRIX
            if row["recommendation"] == "keep_as_is"
        ]

    def not_using_converged_brain(self) -> list[str]:
        positive_markers = (
            "orb_brain_convergence_orchestrator_service",
            "build_brain_decision",
            "orb_unified_brain_gateway",
        )
        return [
            row["route"]
            for row in ROUTE_CONVERGENCE_MATRIX
            if row["recommendation"] in ("converge_soon", "retire", "phase_2d_safety")
            and not any(marker in row["current_brain_orchestrator"] for marker in positive_markers)
        ]

    def missing_context_routes(self) -> list[str]:
        return [
            row["route"]
            for row in ROUTE_CONVERGENCE_MATRIX
            if row["recommendation"] == "add_context"
        ]

    def missing_tests_routes(self) -> list[str]:
        return [
            row["route"]
            for row in ROUTE_CONVERGENCE_MATRIX
            if row["recommendation"] == "add_tests"
        ]

    def legacy_retire_routes(self) -> list[str]:
        return [
            row["route"]
            for row in ROUTE_CONVERGENCE_MATRIX
            if row["recommendation"] == "retire"
        ]


orb_brain_route_convergence_audit_service = OrbBrainRouteConvergenceAuditService()
