from __future__ import annotations

"""Generate, fill and export ORB Residential templates."""

import base64
import io
import re
from datetime import datetime, timezone
from html import escape
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from services.docx_export_service import docx_export_service
from services.orb_template_library_registry import orb_template_library_registry


class OrbTemplateGenerationService:
    def generate(self, template_id: str, *, title: str | None = None) -> dict[str, Any]:
        template = orb_template_library_registry.get_template(template_id)
        if not template:
            raise ValueError(f"Unknown template: {template_id}")
        payload = dict(template)
        if title:
            payload["title"] = title
        payload["generated_at"] = datetime.now(timezone.utc).isoformat()
        payload["markdown"] = self.to_markdown(payload)
        payload["html_preview"] = self.to_html(payload)
        return payload

    def create_draft(
        self,
        template_id: str,
        *,
        filled_sections: dict[str, str] | None = None,
        title: str | None = None,
    ) -> dict[str, Any]:
        generated = self.generate(template_id, title=title)
        sections = generated.get("sections") or []
        filled = filled_sections or {}
        for section in sections:
            heading = section.get("heading") or ""
            if heading in filled:
                section["content"] = filled[heading]
            else:
                section["content"] = section.get("placeholder") or ""
        generated["filled"] = True
        generated["markdown"] = self.to_markdown(generated, include_content=True)
        generated["html_preview"] = self.to_html(generated, include_content=True)
        return generated

    def export(
        self,
        template_id: str,
        *,
        profile: str = "pdf",
        filled_sections: dict[str, str] | None = None,
        title: str | None = None,
    ) -> dict[str, Any]:
        draft = self.create_draft(template_id, filled_sections=filled_sections, title=title)
        document = {
            "title": draft.get("title"),
            "sections": {
                (s.get("heading") or f"section_{i}"): s.get("content") or s.get("placeholder") or ""
                for i, s in enumerate(draft.get("sections") or [])
            },
        }
        profile = (profile or "pdf").lower()
        if profile == "markdown":
            md = draft.get("markdown") or ""
            return {
                "ok": True,
                "profile": "markdown",
                "media_type": "text/markdown",
                "filename": self._safe_filename(draft.get("title"), "md"),
                "content": md,
                "byte_length": len(md.encode("utf-8")),
            }
        if profile == "html":
            html = draft.get("html_preview") or ""
            return {
                "ok": True,
                "profile": "html",
                "media_type": "text/html",
                "filename": self._safe_filename(draft.get("title"), "html"),
                "content": html,
                "byte_length": len(html.encode("utf-8")),
            }
        if profile == "docx":
            return docx_export_service.export(document=document, title=str(draft.get("title") or "ORB Template"))
        return self._export_pdf(document, title=str(draft.get("title") or "ORB Template"))

    def to_markdown(self, template: dict[str, Any], *, include_content: bool = False) -> str:
        lines = [
            f"# {template.get('title') or 'ORB Template'}",
            "",
            f"**Purpose:** {template.get('purpose') or ''}",
            f"**Category:** {template.get('category') or ''}",
            "",
        ]
        for section in template.get("sections") or []:
            heading = section.get("heading") or "Section"
            lines.append(f"## {heading}")
            lines.append("")
            if include_content and section.get("content"):
                lines.append(str(section["content"]))
            else:
                lines.append(f"*{section.get('prompt') or ''}*")
                lines.append("")
                lines.append(str(section.get("placeholder") or "[Complete this section]"))
            lines.append("")
        lines.extend(
            [
                "---",
                "",
                "**Child voice:** " + str(template.get("child_voice_prompt") or ""),
                "",
                "**Safeguarding:** " + str(template.get("safeguarding_prompt") or ""),
                "",
                "*Generated by ORB Residential — standalone guidance template. Not a live care record.*",
            ]
        )
        return "\n".join(lines)

    def to_html(self, template: dict[str, Any], *, include_content: bool = False) -> str:
        parts = [
            "<!DOCTYPE html><html><head><meta charset='utf-8'>",
            f"<title>{escape(str(template.get('title') or 'ORB Template'))}</title>",
            "<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:2rem auto;padding:0 1rem;line-height:1.5}",
            "h1{font-size:1.5rem}h2{font-size:1.1rem;margin-top:1.5rem;color:#334155}",
            ".meta{color:#64748b;font-size:0.9rem}</style></head><body>",
            f"<h1>{escape(str(template.get('title') or 'ORB Template'))}</h1>",
            f"<p class='meta'>{escape(str(template.get('purpose') or ''))}</p>",
        ]
        for section in template.get("sections") or []:
            heading = escape(str(section.get("heading") or "Section"))
            parts.append(f"<h2>{heading}</h2>")
            if include_content and section.get("content"):
                parts.append(f"<p>{escape(str(section['content']))}</p>")
            else:
                parts.append(f"<p><em>{escape(str(section.get('prompt') or ''))}</em></p>")
                parts.append(f"<p>{escape(str(section.get('placeholder') or '[Complete this section]'))}</p>")
        parts.append(
            "<footer class='meta'><p>ORB Residential standalone template — not linked to live OS records.</p></footer>"
        )
        parts.append("</body></html>")
        return "".join(parts)

    def _export_pdf(self, document: dict[str, Any], *, title: str) -> dict[str, Any]:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=44, leftMargin=44, topMargin=54, bottomMargin=48)
        styles = getSampleStyleSheet()
        story: list[Any] = [
            Paragraph("ORB Residential — practice template", styles["Title"]),
            Paragraph(escape(title), styles["Heading1"]),
            Paragraph(
                f"Generated {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}",
                styles["Normal"],
            ),
            Spacer(1, 12),
        ]
        for key, value in (document.get("sections") or {}).items():
            story.append(Paragraph(escape(str(key)), styles["Heading2"]))
            story.append(Paragraph(escape(str(value or "")), styles["BodyText"]))
            story.append(Spacer(1, 8))
        doc.build(story)
        payload = buffer.getvalue()
        return {
            "ok": True,
            "profile": "pdf",
            "media_type": "application/pdf",
            "filename": self._safe_filename(title, "pdf"),
            "byte_length": len(payload),
            "content_base64": base64.b64encode(payload).decode("ascii"),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "confidentiality_label": "ORB practice template — complete with factual information only",
        }

    def _safe_filename(self, title: str | None, ext: str) -> str:
        base = re.sub(r"[^\w\s-]", "", str(title or "orb_template")).strip().replace(" ", "_")[:80]
        return f"{base or 'orb_template'}.{ext}"


orb_template_generation_service = OrbTemplateGenerationService()
