import { ChronologyEvent } from './types'

export const demoChronologyEvents: ChronologyEvent[] = [
  {
    id: 'chron-log-jamie-school',
    dateTime: '2026-05-13T09:30:00.000Z',
    title: 'Jamie attended school after settled morning routine',
    summary: 'Jamie woke on time, ate breakfast and left for school with staff prompts.',
    fullText: 'Jamie woke on time, ate breakfast and left for Oakbridge Academy with prompts from Abi. Staff noted this as positive education evidence and agreed to praise the routine later in the day.',
    eventType: 'daily_log',
    category: 'Education and daily care',
    severity: 'low',
    sourceType: 'daily_log',
    sourceId: 'log-001',
    youngPersonIds: ['yp-jamie'],
    staffIds: ['staff-abi'],
    homeId: 'home-oak',
    tags: ['education', 'routine', 'positive-outcome', 'daily-record'],
    linkedRecordIds: ['log-001', 'report-lac-jamie-may'],
    evidenceIds: ['ev-jamie-school-attendance'],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 8', label: 'Education and learning', confidence: 'supporting' }],
    safeguardingFlags: [],
    riskFlags: [],
    actionIds: ['act-education-evidence'],
    createdBy: 'staff-abi',
    createdAt: '2026-05-13T09:30:00.000Z',
    updatedAt: '2026-05-13T09:30:00.000Z',
    visibility: 'home',
    citationLabel: '[Daily Log, 13 May 2026, Jamie Taylor, Morning shift]'
  },
  {
    id: 'chron-log-noah-phone',
    dateTime: '2026-05-13T11:20:00.000Z',
    title: 'Noah anxious after phone call before education transport',
    summary: 'Noah needed space after a phone call and staff planned a keywork check-in.',
    fullText: 'Noah was anxious after a phone call and needed space before education transport. Staff recorded contact anxiety as a possible trigger and planned a keywork check-in and risk plan trigger update.',
    eventType: 'daily_log',
    category: 'Emotional wellbeing',
    severity: 'medium',
    sourceType: 'daily_log',
    sourceId: 'log-002',
    youngPersonIds: ['yp-noah'],
    staffIds: ['staff-morgan'],
    homeId: 'home-oak',
    tags: ['contact-anxiety', 'education', 'keywork-needed'],
    linkedRecordIds: ['log-002', 'risk-001'],
    evidenceIds: [],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 12', label: 'Safeguarding and protection', confidence: 'possible' }],
    safeguardingFlags: ['contact anxiety linked to missing vulnerability'],
    riskFlags: ['missing-trigger', 'routine-disruption'],
    actionIds: [],
    createdBy: 'staff-morgan',
    createdAt: '2026-05-13T11:20:00.000Z',
    updatedAt: '2026-05-13T11:20:00.000Z',
    visibility: 'home',
    citationLabel: '[Daily Log, 13 May 2026, Noah Ahmed, Morning shift]'
  },
  {
    id: 'chron-inc-noah-missing',
    dateTime: '2026-05-12T18:40:00.000Z',
    title: 'Noah missing from care concern and safe return',
    summary: 'Noah left the home after an activity cancellation and returned safely with staff support.',
    fullText: 'Noah left the home after refusing a planned activity following the unexpected cancellation of basketball. Staff followed the known safe route, notified police and supported Noah to return safely. Welfare check completed; no injuries reported. Manager review and updated missing protocol required.',
    eventType: 'missing_episode',
    category: 'Safeguarding',
    severity: 'critical',
    sourceType: 'incident',
    sourceId: 'inc-001',
    youngPersonIds: ['yp-noah'],
    staffIds: ['staff-morgan', 'staff-abi'],
    homeId: 'home-oak',
    tags: ['missing', 'safeguarding', 'police-notified', 'manager-review'],
    linkedRecordIds: ['inc-001', 'safe-001', 'risk-001', 'doc-noah-missing-protocol'],
    evidenceIds: ['ev-noah-missing-return'],
    regulationLinks: [
      { regulation: 'Children Homes Regulations 2015 Reg 12', label: 'Safeguarding and protection', confidence: 'direct' },
      { regulation: 'Regulation 44', label: 'Independent visitor oversight', confidence: 'supporting' }
    ],
    safeguardingFlags: ['missing episode', 'exploitation vulnerability'],
    riskFlags: ['missing-from-care', 'unsafe-peer-group', 'routine-disruption'],
    actionIds: ['act-reg44-return-interviews'],
    createdBy: 'staff-morgan',
    createdAt: '2026-05-12T20:15:00.000Z',
    updatedAt: '2026-05-12T20:15:00.000Z',
    visibility: 'restricted',
    citationLabel: '[Incident, 12 May 2026, Noah Ahmed, Manager Review Pending]'
  },
  {
    id: 'chron-safe-noah-exploitation',
    dateTime: '2026-05-12T19:10:00.000Z',
    title: 'Safeguarding chronology updated for missing and exploitation vulnerability',
    summary: 'Police, social worker and CAMHS were linked into Noah safety planning.',
    fullText: 'Safeguarding entry recorded that the missing episode is linked to previous concerns about an unsafe peer group. Police notification completed, social worker updated and safety plan review booked.',
    eventType: 'safeguarding',
    category: 'Safeguarding',
    severity: 'critical',
    sourceType: 'safeguarding',
    sourceId: 'safe-001',
    youngPersonIds: ['yp-noah'],
    staffIds: ['staff-morgan'],
    homeId: 'home-oak',
    tags: ['safeguarding', 'missing', 'external-agencies'],
    linkedRecordIds: ['safe-001', 'inc-001', 'risk-001'],
    evidenceIds: ['ev-noah-missing-return'],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 12', label: 'Safeguarding and protection', confidence: 'direct' }],
    safeguardingFlags: ['active safeguarding concern'],
    riskFlags: ['exploitation-vulnerability', 'missing-from-care'],
    actionIds: ['act-reg44-return-interviews'],
    createdBy: 'staff-morgan',
    createdAt: '2026-05-12T19:10:00.000Z',
    updatedAt: '2026-05-12T19:10:00.000Z',
    visibility: 'restricted',
    citationLabel: '[Safeguarding, 12 May 2026, Noah Ahmed, Police and social worker updated]'
  },
  {
    id: 'chron-log-mia-homework',
    dateTime: '2026-05-12T20:10:00.000Z',
    title: 'Mia completed homework and joined meal preparation',
    summary: 'Mia engaged positively with homework and communal meal preparation.',
    fullText: 'Mia completed homework and joined communal meal preparation. Staff noted this as positive emotional wellbeing and independence evidence, with child voice to be included in Reg 45 quality of care review.',
    eventType: 'positive_outcome',
    category: 'Emotional wellbeing',
    severity: 'low',
    sourceType: 'daily_log',
    sourceId: 'log-003',
    youngPersonIds: ['yp-mia'],
    staffIds: ['staff-ella'],
    homeId: 'home-oak',
    tags: ['child-voice', 'independence', 'wellbeing', 'positive-outcome'],
    linkedRecordIds: ['log-003', 'report-reg45-2026'],
    evidenceIds: ['ev-mia-child-voice'],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 7', label: 'Children wishes and feelings', confidence: 'supporting' }],
    safeguardingFlags: [],
    riskFlags: [],
    actionIds: [],
    createdBy: 'staff-ella',
    createdAt: '2026-05-12T20:10:00.000Z',
    updatedAt: '2026-05-12T20:10:00.000Z',
    visibility: 'home',
    citationLabel: '[Daily Log, 12 May 2026, Mia Roberts, Evening shift]'
  },
  {
    id: 'chron-risk-noah-review',
    dateTime: '2026-05-11T10:00:00.000Z',
    title: 'Noah missing risk assessment review overdue',
    summary: 'Risk review date passed before the missing episode; controls need manager oversight.',
    fullText: 'Noah missing from care risk assessment identifies elevated missing risk when routines change or contact is disrupted. Review was due on 11 May and is overdue, requiring manager sign-off and updated controls.',
    eventType: 'risk_review',
    category: 'Risk',
    severity: 'high',
    sourceType: 'manager_review',
    sourceId: 'risk-001',
    youngPersonIds: ['yp-noah'],
    staffIds: ['staff-ella'],
    homeId: 'home-oak',
    tags: ['risk-review', 'missing', 'overdue-manager-review'],
    linkedRecordIds: ['risk-001', 'inc-001'],
    evidenceIds: [],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 12', label: 'Safeguarding and protection', confidence: 'direct' }],
    safeguardingFlags: ['risk review overdue'],
    riskFlags: ['missing-from-care', 'routine-disruption'],
    actionIds: ['act-reg44-return-interviews'],
    createdBy: 'staff-ella',
    createdAt: '2026-05-11T10:00:00.000Z',
    updatedAt: '2026-05-11T10:00:00.000Z',
    visibility: 'leadership',
    citationLabel: '[Risk Review, 11 May 2026, Noah Ahmed, Overdue]'
  },
  {
    id: 'chron-inc-jamie-peer',
    dateTime: '2026-05-10T16:15:00.000Z',
    title: 'Jamie peer disagreement resolved through restorative conversation',
    summary: 'Jamie argued about console time, apologised and agreed to the gaming rota.',
    fullText: 'Jamie argued with a peer over console time and threw a controller onto the sofa. Staff used time out and restorative conversation. No injuries. Manager asked staff to review the rota and consistency.',
    eventType: 'incident',
    category: 'Behaviour support',
    severity: 'medium',
    sourceType: 'incident',
    sourceId: 'inc-002',
    youngPersonIds: ['yp-jamie'],
    staffIds: ['staff-abi'],
    homeId: 'home-oak',
    tags: ['behaviour-support', 'restorative-practice', 'manager-review'],
    linkedRecordIds: ['inc-002', 'mgr-002'],
    evidenceIds: ['ev-manager-review-gaming-rota'],
    regulationLinks: [{ regulation: 'Children Homes Regulations 2015 Reg 13', label: 'Leadership and management', confidence: 'supporting' }],
    safeguardingFlags: [],
    riskFlags: ['peer-conflict'],
    actionIds: [],
    createdBy: 'staff-abi',
    createdAt: '2026-05-10T17:00:00.000Z',
    updatedAt: '2026-05-11T14:00:00.000Z',
    visibility: 'home',
    citationLabel: '[Incident, 10 May 2026, Jamie Taylor, Manager rota review]'
  },
  {
    id: 'chron-safe-jamie-contact',
    dateTime: '2026-05-08T16:30:00.000Z',
    title: 'Jamie reported feeling pressured during family call',
    summary: 'Staff debriefed Jamie and informed the contact supervisor.',
    fullText: 'Jamie told staff he felt pressured during a family call. Staff completed a debrief, informed the contact supervisor and agreed to review the support plan with the social worker if worries continue.',
    eventType: 'family_contact',
    category: 'Family time',
    severity: 'medium',
    sourceType: 'safeguarding',
    sourceId: 'safe-002',
    youngPersonIds: ['yp-jamie'],
    staffIds: ['staff-ella'],
    homeId: 'home-oak',
    tags: ['family-time', 'contact-anxiety', 'child-voice'],
    linkedRecordIds: ['safe-002'],
    evidenceIds: [],
    regulationLinks: [
      { regulation: 'Children Homes Regulations 2015 Reg 9', label: 'Contact and access to services', confidence: 'direct' },
      { regulation: 'Children Homes Regulations 2015 Reg 12', label: 'Safeguarding and protection', confidence: 'possible' }
    ],
    safeguardingFlags: ['family contact worry'],
    riskFlags: ['contact-anxiety'],
    actionIds: ['act-jamie-contact-plan'],
    createdBy: 'staff-ella',
    createdAt: '2026-05-08T16:45:00.000Z',
    updatedAt: '2026-05-08T16:45:00.000Z',
    visibility: 'restricted',
    citationLabel: '[Safeguarding, 8 May 2026, Jamie Taylor, Family contact worry]'
  },
  {
    id: 'chron-reg44-april',
    dateTime: '2026-05-01T10:00:00.000Z',
    title: 'Reg 44 April finding: return interview audit trail',
    summary: 'Independent visitor found return interview outcomes were not consistently linked into chronology.',
    fullText: 'Reg 44 April 2026 finding 3 states that return interview outcomes following missing episodes are not consistently visible in the young person chronology. The action plan requires source records, manager review and evidence links.',
    eventType: 'reg44_finding',
    category: 'Regulatory oversight',
    severity: 'high',
    sourceType: 'reg44_report',
    sourceId: 'doc-reg44-apr-2026',
    youngPersonIds: ['yp-noah'],
    staffIds: ['staff-ella'],
    homeId: 'home-oak',
    tags: ['reg44', 'audit-trail', 'evidence-gap', 'action-required'],
    linkedRecordIds: ['doc-reg44-apr-2026', 'inc-001', 'safe-001'],
    evidenceIds: ['ev-reg44-april-finding-3'],
    regulationLinks: [{ regulation: 'Regulation 44', label: 'Independent visitor report', confidence: 'direct' }],
    safeguardingFlags: ['regulatory safeguarding oversight'],
    riskFlags: ['missing-from-care'],
    actionIds: ['act-reg44-return-interviews'],
    createdBy: 'staff-ella',
    createdAt: '2026-05-01T10:00:00.000Z',
    updatedAt: '2026-05-01T10:00:00.000Z',
    visibility: 'leadership',
    citationLabel: '[Reg 44, April 2026, Finding 3]'
  },
  {
    id: 'chron-reg45-prep',
    dateTime: '2026-05-10T15:00:00.000Z',
    title: 'Reg 45 draft requires professional and family feedback',
    summary: 'Annual quality of care review is in draft and needs external feedback evidence.',
    fullText: 'Reg 45 draft quality of care review includes child voice and care outcomes, but professional and family feedback remains incomplete. Manager action created to collect social worker, virtual school and family views where appropriate.',
    eventType: 'reg45_evidence',
    category: 'Regulatory reporting',
    severity: 'medium',
    sourceType: 'reg45_report',
    sourceId: 'doc-reg45-draft-2026',
    youngPersonIds: ['yp-jamie', 'yp-noah', 'yp-mia'],
    staffIds: ['staff-ella'],
    homeId: 'home-oak',
    tags: ['reg45', 'quality-of-care', 'feedback', 'draft-review-required'],
    linkedRecordIds: ['doc-reg45-draft-2026', 'report-reg45-2026'],
    evidenceIds: ['ev-mia-child-voice'],
    regulationLinks: [{ regulation: 'Regulation 45', label: 'Quality of care review', confidence: 'direct' }],
    safeguardingFlags: [],
    riskFlags: [],
    actionIds: ['act-reg45-feedback'],
    createdBy: 'staff-ella',
    createdAt: '2026-05-10T15:00:00.000Z',
    updatedAt: '2026-05-10T15:00:00.000Z',
    visibility: 'leadership',
    citationLabel: '[Reg 45, 2026 draft, Feedback evidence required]'
  },
  {
    id: 'chron-doc-jamie-lac',
    dateTime: '2026-05-13T12:20:00.000Z',
    title: 'Jamie LAC review pack uploaded',
    summary: 'LAC review pack uploaded with education and family time evidence still being gathered.',
    fullText: 'Jamie LAC review pack was uploaded for May 2026. It includes recent daily care and education evidence, with actions to attach school attendance confirmation and child voice about the timetable.',
    eventType: 'lac_review',
    category: 'Review and reporting',
    severity: 'medium',
    sourceType: 'lac_review',
    sourceId: 'doc-jamie-lac-review',
    youngPersonIds: ['yp-jamie'],
    staffIds: ['staff-abi'],
    homeId: 'home-oak',
    tags: ['lac-review', 'education', 'family-time', 'draft-review-required'],
    linkedRecordIds: ['doc-jamie-lac-review', 'report-lac-jamie-may'],
    evidenceIds: ['ev-jamie-school-attendance'],
    regulationLinks: [{ regulation: 'Care Planning Regulations', label: 'Looked-after review evidence', confidence: 'supporting' }],
    safeguardingFlags: [],
    riskFlags: ['contact-anxiety'],
    actionIds: ['act-education-evidence'],
    createdBy: 'staff-abi',
    createdAt: '2026-05-13T12:20:00.000Z',
    updatedAt: '2026-05-13T12:20:00.000Z',
    visibility: 'home',
    citationLabel: '[LAC Review, May 2026, Jamie Taylor, Draft pack]'
  }
]
