"""ORB expert scenario family taxonomy — structured residential children's home events."""

from __future__ import annotations

from typing import Any


def _family(
    id: str,
    label: str,
    description: str,
    *,
    triggers: list[str],
    red_flags: list[str],
    risk: str = "medium",
    roles: list[str] | None = None,
    anchors: list[str] | None = None,
    lenses: list[str] | None = None,
    records: list[str] | None = None,
    actions: list[str] | None = None,
    oversight: list[str] | None = None,
    reg44: list[str] | None = None,
    nvq: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "description": description,
        "common_triggers": triggers,
        "red_flags": red_flags,
        "default_risk_level": risk,
        "likely_roles": roles or ["support_worker", "registered_manager", "reg44_visitor"],
        "likely_source_anchors": anchors or ["dfe_childrens_homes_regulations_guide", "working_together_safeguarding"],
        "expected_lenses": lenses or ["safeguarding", "recording", "manager oversight"],
        "typical_records": records or ["incident record", "daily log", "chronology"],
        "typical_actions": actions or ["risk review", "manager review", "multi-agency update"],
        "typical_manager_oversight": oversight or ["sight and review within timescale", "actions owned"],
        "typical_reg44_questions": reg44 or ["What changed after last incident?", "Is child voice visible?"],
        "typical_nvq_learning": nvq or ["reflective account boundaries", "factual recording"],
    }


ORB_SCENARIO_FAMILIES: list[dict[str, Any]] = [
    _family(
        "missing_from_care",
        "Missing from care",
        "Child absent from placement without permission or not returned as expected.",
        triggers=["missing", "absent", "not returned", "AWOL", "run away"],
        red_flags=["unknown adult", "vehicle", "repeated episodes", "no return conversation"],
        risk="critical",
        anchors=["missing_from_care_guidance", "working_together_safeguarding", "childrens_homes_regulations_2015", "ofsted_sccif_childrens_homes"],
        lenses=["immediate safety", "exploitation", "return conversation", "chronology"],
        reg44=["Is missing plan current?", "Police/SW updated?"],
    ),
    _family(
        "late_return",
        "Late return",
        "Child returned later than agreed without full welfare check completed.",
        triggers=["late back", "hours late", "curfew"],
        red_flags=["intoxication", "new items", "refuses to say where"],
        risk="high",
        anchors=["missing_from_care_guidance"],
    ),
    _family(
        "repeated_missing",
        "Repeated missing episodes",
        "Pattern of missing indicating escalating risk or plan failure.",
        triggers=["third time", "again missing", "pattern", "third episode", "repeated missing"],
        red_flags=["CSE", "CCE", "county lines", "hotel", "no return conversation", "weak closure language"],
        risk="critical",
        anchors=["missing_from_care_guidance", "working_together_safeguarding"],
        lenses=["pattern not single incident", "exploitation lens", "push/pull factors", "contextual safeguarding"],
        records=["missing trend review", "return home conversation", "chronology update", "missing risk assessment update"],
        actions=["missing plan review", "social worker update", "multi-agency escalation", "local missing-from-care procedure"],
        oversight=["trend review", "plan refresh", "multi-agency meeting", "manager oversight note"],
        reg44=["Trend visible in chronology?", "Plan reviewed?", "What changed since last episode?"],
    ),
    _family(
        "unknown_adult_vehicle",
        "Unknown adult / vehicle",
        "Unidentified adult or vehicle linked to child leaving or contact.",
        triggers=["unknown adult", "car pulled up", "vehicle", "stranger outside"],
        red_flags=["coercion", "immediate departure", "gifts", "coded language"],
        risk="critical",
        anchors=["missing_from_care_guidance", "working_together_safeguarding"],
        lenses=["immediate safeguarding", "exploitation", "restrictive practice boundary"],
    ),
    _family(
        "cse_concern",
        "CSE concern",
        "Indicators of child sexual exploitation after incident or disclosure.",
        triggers=["CSE", "exploitation", "older boyfriend", "gifts", "hotel"],
        red_flags=["secrecy", "new phone", "trauma bond"],
        risk="critical",
        anchors=["working_together_safeguarding", "missing_from_care_guidance"],
    ),
    _family(
        "cce_county_lines",
        "CCE / county lines concern",
        "Criminal exploitation or county lines indicators.",
        triggers=["county lines", "debt", "package", "train station"],
        red_flags=["unknown adults", "money", "violence threat"],
        risk="critical",
    ),
    _family(
        "online_grooming",
        "Online grooming concern",
        "Online contact with risky adult or harmful content sharing.",
        triggers=["grooming", "online", "image sharing", "Snapchat"],
        red_flags=["secrecy", "meeting unknown adult"],
        risk="high",
        anchors=["working_together_safeguarding", "kcsie"],
    ),
    _family(
        "disclosure_abuse",
        "Disclosure of abuse",
        "Child discloses current or recent abuse.",
        triggers=["told me", "disclosure", "abuse", "hurt me"],
        red_flags=["partial disclosure", "withdrawal", "fear of consequences"],
        risk="critical",
        anchors=["working_together_safeguarding", "provider_safeguarding_policy"],
        lenses=["safeguarding", "child voice", "evidence preservation"],
    ),
    _family(
        "historic_abuse_disclosure",
        "Historic abuse disclosure",
        "Disclosure of non-recent abuse requiring sensitive response.",
        triggers=["when I was younger", "years ago", "historic"],
        red_flags=["minimising", "shame", "family loyalty"],
        risk="high",
    ),
    _family(
        "allegation_staff",
        "Allegation against staff",
        "Child alleges harm by staff member.",
        triggers=["staff hurt", "grabbed me", "allegation against staff"],
        red_flags=["witnesses", "injury", "restraint overlap"],
        risk="critical",
        anchors=["working_together_safeguarding", "provider_safeguarding_policy"],
        oversight=["LADO consideration", "separation of roles", "preserve evidence"],
    ),
    _family(
        "allegation_peer",
        "Allegation against another child",
        "Harm alleged between children in the home.",
        triggers=["another child", "peer", "hit me"],
        red_flags=["power imbalance", "sexual harm", "repeated"],
        risk="high",
    ),
    _family(
        "peer_on_peer_harm",
        "Peer-on-peer harm",
        "Physical or emotional harm between peers.",
        triggers=["fight", "bullying", "intimidation"],
        red_flags=["weapon", "sexual element", "group dynamic"],
        risk="high",
    ),
    _family(
        "self_harm_disclosure",
        "Self-harm disclosure",
        "Child discloses self-harm or staff discover injury.",
        triggers=["self-harm", "cutting", "burns"],
        red_flags=["ligature", "suicidal ideation", "hidden"],
        risk="critical",
        anchors=["nice_self_harm", "working_together_safeguarding"],
    ),
    _family(
        "ligature_concern",
        "Ligature concern",
        "Ligature materials or attempt identified.",
        triggers=["ligature", "rope", "belt", "hanging"],
        red_flags=["suicide plan", "isolation"],
        risk="critical",
    ),
    _family(
        "weapon_disclosure",
        "Weapon disclosure",
        "Child has or mentions weapon.",
        triggers=["knife", "weapon", "blade"],
        red_flags=["intent", "gang link"],
        risk="critical",
    ),
    _family(
        "physical_intervention",
        "Physical intervention / restraint",
        "Restrictive physical intervention used or considered.",
        triggers=["restraint", "physical intervention", "held"],
        red_flags=["injury complaint", "no debrief", "after missing return"],
        risk="high",
        anchors=["dfe_childrens_homes_regulations_guide", "provider_restraint_policy", "childrens_homes_regulations_2015"],
        lenses=["proportionality", "debrief", "recording", "therapeutic repair"],
    ),
    _family(
        "restraint_injury_complaint",
        "Restraint injury complaint",
        "Child or parent reports injury following restraint.",
        triggers=["bruise after restraint", "hurt during restraint"],
        red_flags=["weak record", "no body map", "conflicting accounts"],
        risk="critical",
    ),
    _family(
        "repeated_restraint_trend",
        "Repeated restraint trend",
        "Pattern of restraint indicating plan or practice concern.",
        triggers=["again restrained", "third restraint", "trend"],
        red_flags=["same child", "same staff", "no BSP review"],
        risk="high",
        reg44=["Is trend visible?", "What learning occurred?"],
    ),
    _family(
        "medication_refusal",
        "Medication refusal",
        "Child refuses prescribed medication.",
        triggers=["refused medication", "won't take tablets"],
        red_flags=["controlled drug", "mental health med", "restraint overlap"],
        risk="high",
        anchors=["provider_medication_policy", "childrens_homes_regulations_2015"],
    ),
    _family(
        "medication_error",
        "Medication error",
        "Wrong dose, wrong child, or missed controlled drug recording.",
        triggers=["wrong dose", "medication error", "missed dose"],
        red_flags=["controlled drug", "overdose", "no GP notified"],
        risk="critical",
        anchors=["provider_medication_policy"],
    ),
    _family(
        "controlled_drug_discrepancy",
        "Controlled drug recording concern",
        "Discrepancy in controlled drug stock or records.",
        triggers=["controlled drug", "discrepancy", "missing tablets"],
        red_flags=["diversion suspicion", "no witness"],
        risk="critical",
    ),
    _family(
        "family_contact_distress",
        "Child distressed after contact",
        "Dysregulation or safeguarding concern following family contact.",
        triggers=["after contact", "distressed", "phone call"],
        red_flags=["threats", "missing link", "gifts from family"],
        risk="medium",
    ),
    _family(
        "child_not_feeling_safe",
        "Child does not feel safe",
        "Child expresses feeling unsafe in placement or with staff/peers.",
        triggers=["don't feel safe", "not safe here"],
        red_flags=["names staff", "refuses room"],
        risk="high",
    ),
    _family(
        "poor_daily_log",
        "Poor daily log",
        "Daily record lacks facts, child voice, or proportionate detail.",
        triggers=["daily log", "diary", "shift record"],
        red_flags=["labels", "opinion only", "copy paste"],
        risk="medium",
        lenses=["recording quality", "Ofsted evidence"],
        anchors=["dfe_childrens_homes_regulations_guide", "ofsted_sccif_childrens_homes"],
    ),
    _family(
        "opinion_based_record",
        "Opinion-based incident record",
        "Incident record uses judgemental or punitive language.",
        triggers=["manipulative", "attention seeking", "attention-seeking", "chose to kick off"],
        red_flags=["no child voice", "no timeline", "self-harm labelled as attention-seeking"],
        risk="medium",
        lenses=["observable behaviour", "function of behaviour", "unmet need", "trauma-informed recording"],
        records=["factual incident rewrite", "staff response", "context and trigger", "child voice"],
        oversight=["supervision on recording standards", "training on therapeutic language"],
    ),
    _family(
        "missing_child_voice",
        "Missing child voice in records",
        "Records lack child's words, views, or participation.",
        triggers=["no child voice", "didn't capture quote"],
        red_flags=["high safeguarding case", "contact decision"],
        risk="medium",
    ),
    _family(
        "weak_manager_oversight",
        "Weak manager oversight",
        "Manager review, actions, or learning not evidenced.",
        triggers=["manager not sighted", "no review", "actions open"],
        red_flags=["repeated theme", "Reg 44 action open"],
        risk="high",
        anchors=["childrens_homes_regulations_2015", "ofsted_sccif_childrens_homes"],
        reg44=["Can I see manager challenge?", "Impact of actions?"],
    ),
    _family(
        "no_chronology_entry",
        "No chronology entry",
        "Significant event not reflected in chronology.",
        triggers=["chronology", "timeline", "pattern"],
        red_flags=["repeated missing", "restraint trend"],
        risk="medium",
    ),
    _family(
        "record_no_further_issues",
        "Record says no further issues despite concerns",
        "Closure language mismatches unresolved risk.",
        triggers=["no further issues", "all fine now", "resolved", "settled with no concerns", "nothing else to report"],
        red_flags=["ongoing risk", "open actions", "repeated missing", "missing overnight"],
        risk="high",
        lenses=["challenge weak closure", "observation-based recording", "open risks"],
        records=["post-incident observations", "young person presentation", "staff response and follow-up"],
        oversight=["manager review where risk remains", "chronology update"],
    ),
    _family(
        "reg44_action_not_closed",
        "Reg 44 repeated action not closed",
        "Independent visitor action remains open across visits.",
        triggers=["Reg 44", "action not closed", "repeat action"],
        red_flags=["same theme", "no impact evidence"],
        risk="high",
        anchors=["childrens_homes_regulations_2015", "ofsted_sccif_childrens_homes"],
        reg44=["Why still open?", "What evidence of change?"],
    ),
    _family(
        "reg45_weak_impact",
        "Reg 45 review lacks impact",
        "Quality of care review does not show impact on child's experience.",
        triggers=["Reg 45", "weak review", "no impact"],
        red_flags=["template", "no child voice"],
        risk="medium",
    ),
    _family(
        "ri_governance_drift",
        "RI governance drift",
        "Responsible individual oversight not challenging repeated risk themes.",
        triggers=["RI", "governance", "provider drift", "theme across homes"],
        red_flags=["repeated restraint", "missing trend"],
        risk="high",
        roles=["responsible_individual", "provider"],
    ),
    _family(
        "ofsted_notification_uncertainty",
        "Ofsted notification uncertainty",
        "Uncertainty whether incident requires notification.",
        triggers=["notify Ofsted", "serious event", "notification"],
        red_flags=["injury", "police", "allegation"],
        risk="high",
        anchors=["childrens_homes_regulations_2015", "dfe_childrens_homes_regulations_guide"],
    ),
    _family(
        "school_refusal",
        "School refusal",
        "Child refusing education attendance.",
        triggers=["school refusal", "refused school", "refused to go to school", "won't go to school"],
        red_flags=["exclusion", "bullying", "after contact"],
        risk="medium",
        anchors=["send_code_of_practice"],
    ),
    _family(
        "autism_communication_missed",
        "Autism-aware communication missed",
        "Communication need not reflected in approach or record.",
        triggers=["autism", "sensory", "meltdown", "literal"],
        red_flags=["restraint", "punitive language"],
        risk="medium",
        anchors=["dfe_childrens_homes_regulations_guide"],
    ),
    _family(
        "gdd_communication_missed",
        "GDD / adaptive communication missed",
        "Adaptive communication or capacity not considered.",
        triggers=["GDD", "non-verbal", "Makaton", "PECS"],
        red_flags=["consent assumed", "restraint"],
        risk="medium",
    ),
    _family(
        "room_search_confiscation",
        "Room search / confiscation concern",
        "Search or confiscation without clear rationale or rights balance.",
        triggers=["room search", "confiscated phone", "door blocked"],
        red_flags=["privacy", "trauma trigger"],
        risk="medium",
        anchors=["provider_restraint_policy"],
    ),
    _family(
        "whistleblowing",
        "Whistleblowing concern",
        "Staff raises concern about practice or cover-up.",
        triggers=["whistleblow", "covered up", "not reporting"],
        red_flags=["retaliation fear", "manager involved"],
        risk="high",
    ),
    _family(
        "nvq_reflective_restraint",
        "NVQ reflective account — restraint",
        "Learner seeks evidence mapping from restraint incident.",
        triggers=["reflective account", "Level 3", "restraint incident"],
        red_flags=["overclaiming role", "invented actions"],
        risk="medium",
        anchors=["academy_nvq_source_pack", "provider_restraint_policy"],
        roles=["nvq_learner", "nvq_assessor"],
        nvq=["authenticity boundary", "witness testimony", "what not to write"],
    ),
    _family(
        "nvq_assessor_missing",
        "NVQ assessor professional discussion — missing",
        "Assessor probes authenticity and evidence from missing episode.",
        triggers=["professional discussion", "assessor", "missing episode"],
        red_flags=["overclaiming", "missing return conversation evidence"],
        risk="medium",
        anchors=["academy_nvq_source_pack", "missing_from_care_guidance"],
        roles=["nvq_assessor"],
    ),
    _family(
        "level5_governance_evidence",
        "Level 5 leadership evidence — governance drift",
        "Manager seeks Level 5 evidence from governance/oversight themes.",
        triggers=["Level 5", "leadership evidence", "governance"],
        red_flags=["invented outcomes", "no impact evidence"],
        risk="medium",
        anchors=["academy_nvq_source_pack", "ofsted_sccif_childrens_homes"],
        roles=["registered_manager", "deputy_manager"],
    ),
    _family(
        "uasc_missing",
        "UASC missing concern",
        "Unaccompanied asylum-seeking child missing with trafficking/exploitation lens.",
        triggers=["UASC", "trafficking", "immigration"],
        red_flags=["unknown adult", "debt", "language barrier"],
        risk="critical",
    ),
    _family(
        "lgbtq_support",
        "LGBTQ+ identity / support concern",
        "Identity-related safety or affirmation need.",
        triggers=["LGBTQ", "trans", "misgendered", "bullying"],
        red_flags=["misgendering", "self-harm", "bullying"],
        anchors=["equality_act_2010"],
        risk="medium",
    ),
    _family(
        "cultural_religious_need",
        "Cultural / religious need missed",
        "Cultural or religious need not met in care or recording.",
        triggers=["halal", "prayer", "cultural", "religious"],
        red_flags=["distress", "care plan gap"],
        risk="medium",
        anchors=["equality_act_2010"],
    ),
    _family(
        "body_map_not_completed",
        "Body map not completed",
        "Injury recorded without body map or unclear explanation.",
        triggers=["bruise", "injury", "body map"],
        red_flags=["restraint", "allegation"],
        risk="high",
    ),
    _family(
        "conflicting_staff_accounts",
        "Conflicting staff accounts",
        "Staff versions of incident do not align.",
        triggers=["conflicting", "different account", "disagree what happened"],
        red_flags=["allegation", "restraint"],
        risk="high",
    ),
    _family(
        "outdated_risk_plans",
        "Outdated risk / BSP / missing plan",
        "Plans not updated after changed risk.",
        triggers=["outdated plan", "not reviewed", "BSP old"],
        red_flags=["repeated incident"],
        risk="medium",
    ),
    _family(
        "advocacy_complaint",
        "Advocacy / complaint request",
        "Child requests advocate or wishes to complain.",
        triggers=["advocate", "complaint", "rights"],
        red_flags=["against staff", "not followed up"],
        risk="medium",
    ),
    _family(
        "social_worker_complaint_records",
        "Social worker complaint about records",
        "Social worker challenges record quality or timeliness.",
        triggers=["social worker", "records poor", "not updated"],
        red_flags=["late records", "no child voice"],
        risk="high",
        roles=["registered_manager", "social_worker"],
    ),
    _family(
        "parent_complaint_restraint",
        "Parent complaint about restraint",
        "Parent challenges restraint or injury.",
        triggers=["parent complaint", "restraint complaint"],
        red_flags=["injury", "weak record"],
        risk="high",
    ),
    _family(
        "night_shift_response",
        "Night shift poor response",
        "Delayed or weak response during night/weekend.",
        triggers=["night shift", "weekend", "on-call"],
        red_flags=["manager absent", "agency staff"],
        risk="high",
    ),
    _family(
        "agency_handover",
        "Agency staff poor handover",
        "Agency worker lacks context; handover weak.",
        triggers=["agency", "handover", "bank staff"],
        red_flags=["missing context", "incident repeat"],
        risk="medium",
    ),
    _family(
        "community_complaint",
        "Community / police complaint",
        "External complaint about child or staff in community.",
        triggers=["neighbour", "police called", "community"],
        red_flags=["reputation", "safeguarding"],
        risk="medium",
    ),
    _family(
        "assault_staff",
        "Assault on staff",
        "Child assaults staff member.",
        triggers=["assault staff", "hit staff", "spat"],
        red_flags=["injury", "weapon", "restraint follow-up"],
        risk="high",
    ),
    _family(
        "property_damage",
        "Damage to property",
        "Significant property damage during dysregulation.",
        triggers=["smashed", "damage", "broken window"],
        red_flags=["escalation", "injury risk"],
        risk="medium",
    ),
    _family(
        "reg44_triangulation",
        "Reg 44 visitor triangulation",
        "Visitor seeks to triangulate records, child voice, and actions.",
        triggers=["triangulation", "Reg 44 visitor", "independent visitor"],
        red_flags=["records mismatch", "open actions"],
        roles=["reg44_visitor"],
        reg44=["Records match chronology?", "Child experience?", "Actions closed?"],
        risk="medium",
    ),
    _family(
        "rm_action_owner",
        "RM asks for action owner / timescale",
        "Registered manager needs clear ownership and timescales.",
        triggers=["action owner", "timescale", "who is doing"],
        red_flags=["vague actions", "no deadline"],
        roles=["registered_manager"],
        risk="medium",
    ),
]
