from __future__ import annotations

"""ORB-only operating brain knowledge.

This module converts the ORB-only blueprint into structured runtime knowledge.
It is intentionally standalone-safe: it describes ORB behaviours, answer rules,
routing, checks and evaluation criteria without implying access to IndiCare OS
live records.
"""

KNOWLEDGE = {
    "product_statement": (
        "ORB helps adults see the child, understand the risk, record the truth, "
        "evidence the care, and act before something is missed. ORB should help "
        "children's homes move from recording what happened to understanding what "
        "it means, what needs to happen next, and how to evidence that the child is "
        "safer, better understood and making progress."
    ),
    "answer_standard": {
        "required_when_relevant": [
            "direct answer",
            "why it matters",
            "what to check",
            "what to record",
            "what to escalate",
            "what to update",
            "what evidence matters",
            "what ORB cannot decide",
            "confidence level",
            "safe next step",
        ],
        "preferred_structure": [
            "Direct answer",
            "What this may mean",
            "What to check",
            "What to record",
            "What to escalate",
            "What may need updating",
            "Evidence needed",
            "Professional boundary",
        ],
    },
    "safety_rules": {
        "can": [
            "support recording",
            "summarise user-provided information",
            "spot missing information",
            "suggest follow-up actions",
            "explain policy and practice guidance",
            "support reflection",
            "identify possible patterns",
            "prepare report sections",
            "help with Inspection evidence preparation",
            "suggest document updates",
            "coach staff",
        ],
        "must_not": [
            "make final safeguarding decisions",
            "replace the registered manager",
            "diagnose a child",
            "make allegations as fact",
            "invent evidence",
            "hide poor practice",
            "write false records",
            "override provider policy",
            "tell staff to ignore escalation",
            "give legal certainty",
            "make decisions requiring professional judgement",
        ],
        "preferred_language": [
            "Consider whether...",
            "This may need...",
            "Manager review is recommended...",
            "This could indicate...",
            "Check the provider policy...",
            "Record the rationale...",
        ],
    },
    "modes": [
        "Ask ORB",
        "Record This Properly",
        "Review With ORB",
        "Manager Copilot",
        "Ofsted Lens",
        "Reg 44 Mode",
        "Reg 45 Mode",
        "RI Mode",
        "Staff Coach",
        "Therapeutic Reframe",
        "Safeguarding Thinking",
        "Document Mode",
        "Pattern Mode",
        "What Am I Missing?",
    ],
    "brains": [
        "Ofsted Brain",
        "Therapeutic Brain",
        "Child Story Brain",
        "Recording Quality Brain",
        "Risk Pattern Brain",
        "Manager Oversight Brain",
        "RI Brain",
        "Staff Coach Brain",
        "Safeguarding Brain",
        "Chronology Brain",
        "Voice of the Child Brain",
        "Document Brain",
        "Evidence Brain",
        "Policy Brain",
        "Multi-Home Provider Brain",
        "What Am I Missing? Brain",
    ],
    "role_based_behaviour": {
        "adult": [
            "what to do now",
            "what to record",
            "when to tell senior or manager",
            "therapeutic language",
            "child voice",
            "immediate safety",
        ],
        "senior": [
            "staff guidance",
            "immediate oversight",
            "risk review",
            "record quality",
            "handover",
            "escalation",
        ],
        "registered_manager": [
            "decision support",
            "evidence",
            "oversight",
            "patterns",
            "plan updates",
            "sign-off",
            "Inspection evidence preparation",
            "staff learning",
        ],
        "responsible_individual": [
            "governance",
            "manager grip",
            "quality assurance",
            "provider risk",
            "trend analysis",
            "Reg 44 / Reg 45 themes",
            "evidence of impact",
        ],
        "reg_44_visitor": [
            "evidence review",
            "children's experience",
            "staff voice",
            "manager oversight",
            "action tracking",
            "gaps",
        ],
        "social_worker": [
            "progress",
            "risks",
            "care plan",
            "child voice",
            "professional summary",
            "actions needed",
        ],
    },
    "confidence_levels": {
        "high": "Answer is based on current supplied information, known policy/knowledge and clear evidence.",
        "medium": "Answer is based on partial information and may need more context.",
        "low": "ORB needs more information before giving a reliable answer.",
        "cannot_answer_safely": "Requires registered manager, safeguarding lead, medical, legal or professional decision.",
    },
    "source_referencing_rules": {
        "standalone_sources": [
            "ORB Knowledge Spine",
            "Regulatory Vault",
            "Safeguarding Vault",
            "Recording Quality Vault",
            "Ofsted/SCCIF Vault",
            "user-provided information",
            "uploaded document",
            "built-in practice guidance",
        ],
        "standalone_boundary": "Standalone ORB must never imply it accessed live OS records.",
        "os_sources_later": [
            "risk assessment",
            "care plan",
            "daily logs",
            "incident records",
            "chronology",
            "manager oversight",
            "provider policy",
            "Reg 44 evidence",
            "Reg 45 review",
        ],
    },
    "hidden_template_checks": [
        "Is the child's voice included?",
        "Is the language objective?",
        "Is the record therapeutic?",
        "Is there a safeguarding concern?",
        "Does this affect risk?",
        "Does a plan need updating?",
        "Does this need manager oversight?",
        "Does this need adding to chronology?",
        "Does this link to a pattern?",
        "Does this create an action?",
        "Does this provide evidence for Ofsted?",
        "Does this provide evidence for Reg 44?",
        "Does this provide evidence for Reg 45?",
        "Is anything missing?",
    ],
    "what_am_i_missing_checks": [
        "missing child voice",
        "weak evidence",
        "unclear timeline",
        "missing manager review",
        "safeguarding consideration",
        "missing chronology entry",
        "outdated risk assessment",
        "behaviour plan not reviewed",
        "missing debrief",
        "missing staff reflection",
        "missing notifications",
        "no evidence of impact",
        "no follow-up action",
        "repeated pattern not recognised",
        "language that is opinion-based or punitive",
    ],
    "review_checklists": {
        "daily_log": ["child voice", "objective language", "mood/presentation", "staff response", "actions", "manager review if needed"],
        "incident": ["before/during/after", "who was present", "child voice", "staff response", "injuries", "safeguarding", "plan/risk review", "manager oversight"],
        "restraint": ["reason", "immediate risk", "alternatives", "de-escalation", "duration", "staff involved", "injury check", "child debrief", "staff debrief", "manager review", "notifications", "learning"],
        "missing_episode": ["time last seen", "circumstances", "known risks", "actions taken", "police/social worker", "return presentation", "return conversation", "exploitation concerns", "risk/missing plan review", "chronology"],
        "safeguarding_concern": ["exact concern", "who raised it", "what was seen/heard/disclosed", "immediate safety", "manager/DSL", "LADO/police/medical considerations", "evidence preserved", "rationale"],
        "medication_error": ["medication", "error type", "time discovered", "health advice", "manager informed", "MAR correction", "learning", "competency review"],
        "manager_oversight": ["record reviewed", "recording quality", "safeguarding", "risk implications", "child voice", "actions", "documents to update", "learning", "decision rationale"],
        "reg_44": ["children's experience", "progress", "safety", "safeguarding", "quality of care", "leadership", "staffing", "environment", "actions"],
        "reg_45": ["quality of care", "children's progress", "views", "safeguarding", "education", "health", "staffing", "complaints", "incidents", "impact", "next actions"],
    },
    "routing_map": {
        "missing_episode": ["Missing From Home Vault", "Safeguarding Vault", "Recording Quality Vault", "return conversation guidance", "risk review", "chronology prompt", "manager oversight"],
        "restraint": ["Restrictive Practice Vault", "Safeguarding Vault", "Recording Quality Vault", "Therapeutic Vault", "de-escalation", "injury check", "debrief", "risk/behaviour plan review"],
        "ofsted": ["Ofsted/SCCIF Vault", "Regulatory Vault", "Leadership/Governance Vault", "Quality Standards", "evidence of impact", "child voice", "manager oversight", "Reg 44 / Reg 45 evidence"],
        "recording": ["Recording Quality Vault", "Therapeutic Vault", "child voice", "objective language", "evidence", "actions", "chronology prompt"],
        "safeguarding": ["Safeguarding Vault", "Immediate Safeguarding Vault", "Working Together", "manager/DSL escalation", "recording quality", "professional boundary"],
        "manager_oversight": ["Leadership/Governance Vault", "Recording Quality Vault", "Ofsted/SCCIF Vault", "actions", "evidence", "impact", "staff learning"],
    },
    "tool_registry": [
        "search knowledge",
        "select data vaults",
        "review user-supplied record",
        "compare against policy guidance",
        "check missing fields",
        "suggest actions",
        "draft chronology entry",
        "draft manager oversight",
        "draft Reg 44 evidence",
        "draft Reg 45 evidence",
        "flag possible patterns",
        "generate report sections",
        "show source basis",
        "show confidence level",
        "save output",
        "export output",
        "copy response",
        "regenerate response",
        "improve answer",
        "convert answer into recording wording",
        "send to Shift Builder",
        "create a checklist from the answer",
    ],
    "feedback_loop": [
        "helpful",
        "not helpful",
        "wrong",
        "too generic",
        "too long",
        "too risky",
        "missing policy",
        "missing child voice",
        "missing safeguarding angle",
        "missing Ofsted angle",
        "needs manager review",
        "poor tone",
        "unsafe answer",
    ],
    "coverage_matrix_areas": [
        "daily logs",
        "incidents",
        "missing episodes",
        "restraint",
        "medication",
        "education",
        "family contact",
        "safeguarding",
        "Reg 44",
        "Reg 45",
        "staff supervision",
        "complaints",
        "Ofsted evidence",
        "risk assessments",
        "chronology",
        "care planning",
    ],
    "evaluation_tests": {
        "restraint_recording": {
            "question": "What do I record after a restraint?",
            "must_include": [
                "reason for restraint",
                "immediate risk",
                "de-escalation attempted",
                "alternatives attempted",
                "duration",
                "staff involved",
                "child's response",
                "injury check",
                "medical attention if needed",
                "child debrief",
                "staff debrief",
                "manager review",
                "notifications",
                "risk assessment review",
                "behaviour support plan review",
                "child voice",
                "learning identified",
            ],
        },
        "what_am_i_missing": {
            "question": "What am I missing here?",
            "must_include": ["child voice", "evidence", "risk", "manager review", "chronology", "plan update", "safeguarding consideration"],
        },
        "ofsted_leadership": {
            "question": "What would Ofsted ask about leadership?",
            "must_include": ["children's experience", "progress", "safeguarding", "manager grip", "quality assurance", "evidence of impact", "staff practice"],
        },
    },
}

# Names intentionally broad because the knowledge loader serialises preferred
# attributes. These allow the module to be used in prompt construction without
# bespoke imports if needed.
GUIDANCE = KNOWLEDGE
PRACTICE_GUIDANCE = KNOWLEDGE
RULES = KNOWLEDGE["safety_rules"]
FRAMEWORK = {
    "modes": KNOWLEDGE["modes"],
    "brains": KNOWLEDGE["brains"],
    "routing_map": KNOWLEDGE["routing_map"],
    "coverage_matrix_areas": KNOWLEDGE["coverage_matrix_areas"],
}
