"""Canonical source registry for ORB citation and stress-test anchoring."""

from __future__ import annotations

from typing import Any

ORB_SOURCE_REGISTRY: list[dict[str, Any]] = [
    {
        "source_id": "dfe_childrens_homes_regulations_guide",
        "label": "Children's Homes Regulations Guide",
        "title": "Guide to the Children's Homes Regulations including the quality standards",
        "publisher": "Department for Education",
        "jurisdiction": "England",
        "source_type": "statutory_guidance",
        "url": "https://www.gov.uk/government/publications/childrens-homes-regulations-including-quality-standards-guide",
        "last_checked": "2026-05-01",
        "applies_to": ["childrens_homes", "quality_standards", "practice", "restraint", "records", "manager_oversight"],
        "exact_text_available": True,
        "exact_chunks_available": True,
        "summary_basis": "DfE guide to regulations and quality standards for children's homes in England.",
        "when_to_cite": [
            "quality standards",
            "care planning",
            "staff practice",
            "restraint proportionality",
            "records and oversight",
            "leadership expectations",
        ],
        "scenario_families": [
            "restraint",
            "recording_evidence",
            "management_governance",
            "behaviour_support",
            "medication_health",
        ],
        "regulation_numbers": ["Reg 12", "Reg 13", "Reg 44", "Reg 45"],
        "citation_labels": ["Children's Homes Regulations Guide", "Quality Standards"],
        "confidence": "high",
        "notes": "Use committed Guide chunks for exact Guide citations; do not cite the separate Regulations 2015 as ingested in this PR.",
        "must_not_overclaim": "Do not guarantee compliance or quote outside committed Guide chunks.",
    },
    {
        "source_id": "childrens_homes_regulations_2015",
        "label": "Children's Homes (England) Regulations 2015",
        "title": "The Children's Homes (England) Regulations 2015",
        "publisher": "UK legislation",
        "jurisdiction": "England",
        "source_type": "legislation",
        "url": "https://www.legislation.gov.uk/uksi/2015/541/contents",
        "last_checked": "2026-05-01",
        "applies_to": ["statutory_duties", "regulation_numbers", "notifications"],
        "exact_text_available": False,
        "structured_chunks_available": True,
        "structured_chunks_module": "services/orb_residential_regulations_2015_ingestion_service.py",
        "summary_basis": "Primary regulations for registered children's homes in England.",
        "when_to_cite": ["regulation reference", "statutory duty", "notification duties"],
        "scenario_families": ["management_governance", "safeguarding", "restraint", "recording_evidence"],
        "regulation_numbers": ["Reg 12", "Reg 13", "Reg 35", "Reg 36", "Reg 44", "Reg 45"],
        "citation_labels": ["Reg 12", "Reg 13", "Reg 44", "Reg 45"],
        "confidence": "high",
        "must_not_overclaim": (
            "Structured Regulations chunks are available offline only; live ORB answers are "
            "not yet wired to retrieve them. Do not guarantee compliance."
        ),
    },
    {
        "source_id": "ofsted_sccif_childrens_homes",
        "label": "SCCIF — Children's Homes",
        "title": "Social care common inspection framework (SCCIF): children's homes",
        "publisher": "Ofsted",
        "jurisdiction": "England",
        "source_type": "inspection_framework",
        "url": "https://www.gov.uk/government/publications/social-care-common-inspection-framework-sccif-childrens-homes",
        "last_checked": "2026-05-01",
        "applies_to": ["inspection", "child_experience", "leadership_impact", "evidence_of_improvement"],
        "exact_text_available": False,
        "structured_chunks_available": True,
        "structured_chunks_module": "services/orb_residential_sccif_ingestion_service.py",
        "summary_basis": "How inspectors evaluate experiences, progress, safety and leadership in children's homes.",
        "when_to_cite": ["ofsted lens", "inspection evidence", "impact of actions", "management grip"],
        "scenario_families": ["management_governance", "recording_evidence", "reg44_reg45"],
        "regulation_numbers": [],
        "citation_labels": ["SCCIF", "Ofsted children's homes framework"],
        "confidence": "high",
        "must_not_overclaim": (
            "Structured SCCIF chunks are available offline only; live ORB answers are "
            "not yet wired to retrieve them. Do not predict inspection grades or outcomes."
        ),
    },
    {
        "source_id": "working_together_safeguarding",
        "label": "Working Together to Safeguard Children",
        "title": "Working Together to Safeguard Children",
        "publisher": "HM Government / Department for Education",
        "jurisdiction": "England",
        "source_type": "statutory_guidance",
        "url": "https://www.gov.uk/government/publications/working-together-to-safeguard-children--2",
        "last_checked": "2026-05-01",
        "applies_to": ["safeguarding", "multi_agency", "information_sharing", "escalation"],
        "exact_text_available": False,
        "summary_basis": "Multi-agency safeguarding duties, professional curiosity and escalation boundaries.",
        "when_to_cite": ["safeguarding disclosure", "referral thinking", "information sharing", "partnership"],
        "scenario_families": ["safeguarding_disclosure", "missing_exploitation", "allegations"],
        "regulation_numbers": [],
        "citation_labels": ["Working Together"],
        "confidence": "high",
        "must_not_overclaim": "Do not state referral is definitely required or definitely not required.",
    },
    {
        "source_id": "missing_from_care_guidance",
        "label": "Children who run away or go missing from home or care",
        "title": "Children who run away or go missing from home or care",
        "publisher": "Department for Education",
        "jurisdiction": "England",
        "source_type": "statutory_guidance",
        "url": "https://www.gov.uk/government/publications/children-who-run-away-or-go-missing-from-home-or-care",
        "last_checked": "2026-05-01",
        "applies_to": ["missing", "return_conversations", "exploitation_indicators", "police_sw"],
        "exact_text_available": False,
        "summary_basis": "Missing episodes, return conversations, prevention, police/social worker involvement.",
        "when_to_cite": ["missing from care", "late return", "repeated missing", "return conversation"],
        "scenario_families": ["missing_exploitation"],
        "regulation_numbers": ["Reg 12"],
        "citation_labels": ["Missing from care guidance"],
        "confidence": "high",
        "must_not_overclaim": "Do not invent missing episode details not provided.",
    },
    {
        "source_id": "children_act_1989",
        "label": "Children Act 1989",
        "title": "Children Act 1989",
        "publisher": "UK legislation",
        "jurisdiction": "England",
        "source_type": "legislation",
        "url": "https://www.legislation.gov.uk/ukpga/1989/41/contents",
        "last_checked": "2026-05-01",
        "applies_to": ["welfare", "parental_responsibility", "looked_after"],
        "exact_text_available": False,
        "summary_basis": "Placeholder — enrich with section-level anchors when exact text is stored.",
        "when_to_cite": ["legal status", "welfare principle"],
        "scenario_families": [],
        "regulation_numbers": [],
        "citation_labels": ["Children Act 1989"],
        "confidence": "medium",
        "must_not_overclaim": "Placeholder card — do not quote sections without exact text.",
    },
    {
        "source_id": "care_planning_placement_regulations",
        "label": "Care Planning, Placement and Case Review Regulations",
        "title": "Care Planning, Placement and Case Review (England) Regulations 2010",
        "publisher": "UK legislation",
        "jurisdiction": "England",
        "source_type": "legislation",
        "url": "https://www.legislation.gov.uk/uksi/2010/959/contents",
        "last_checked": "2026-05-01",
        "applies_to": ["care_planning", "reviews", "placement"],
        "exact_text_available": False,
        "summary_basis": "Placeholder for care planning and review duties.",
        "when_to_cite": ["care plan", "placement review", "LAC review"],
        "scenario_families": ["family_contact"],
        "regulation_numbers": [],
        "citation_labels": ["Care Planning Regulations"],
        "confidence": "medium",
        "must_not_overclaim": "Placeholder — summary basis only.",
    },
    {
        "source_id": "send_code_of_practice",
        "label": "SEND Code of Practice",
        "title": "Special educational needs and disability code of practice",
        "publisher": "Department for Education",
        "jurisdiction": "England",
        "source_type": "statutory_guidance",
        "url": "https://www.gov.uk/government/publications/send-code-of-practice-0-to-25",
        "last_checked": "2026-05-01",
        "applies_to": ["education", "SEN", "EHCP"],
        "exact_text_available": False,
        "summary_basis": "SEN support and EHCP practice in education settings.",
        "when_to_cite": ["school refusal", "SEN", "EHCP", "education plan"],
        "scenario_families": ["education_activities"],
        "regulation_numbers": [],
        "citation_labels": ["SEND Code of Practice"],
        "confidence": "medium",
        "must_not_overclaim": "Practice guidance for education — not children's homes regulations.",
    },
    {
        "source_id": "equality_act_2010",
        "label": "Equality Act 2010",
        "title": "Equality Act 2010",
        "publisher": "UK legislation",
        "jurisdiction": "England",
        "source_type": "legislation",
        "url": "https://www.legislation.gov.uk/ukpga/2010/15/contents",
        "last_checked": "2026-05-01",
        "applies_to": ["equality", "reasonable_adjustments", "protected_characteristics"],
        "exact_text_available": False,
        "summary_basis": "Equality and non-discrimination duties relevant to care practice.",
        "when_to_cite": ["LGBTQ+", "cultural/religious need", "disability adjustments"],
        "scenario_families": ["family_contact"],
        "regulation_numbers": [],
        "citation_labels": ["Equality Act 2010"],
        "confidence": "medium",
        "must_not_overclaim": "Do not provide legal advice on discrimination claims.",
    },
    {
        "source_id": "kcsie",
        "label": "Keeping Children Safe in Education",
        "title": "Keeping children safe in education",
        "publisher": "Department for Education",
        "jurisdiction": "England",
        "source_type": "statutory_guidance",
        "url": "https://www.gov.uk/government/publications/keeping-children-safe-in-education--2",
        "last_checked": "2026-05-01",
        "applies_to": ["education safeguarding", "online safety at school"],
        "exact_text_available": False,
        "summary_basis": "Education safeguarding context — useful when school-linked risks appear.",
        "when_to_cite": ["school bullying", "online risk from school peers"],
        "scenario_families": ["education_activities"],
        "regulation_numbers": [],
        "citation_labels": ["KCSIE"],
        "confidence": "medium",
        "must_not_overclaim": "Primarily applies to education settings; frame as contextual.",
    },
    {
        "source_id": "prevent_duty_guidance",
        "label": "Prevent duty guidance",
        "title": "Prevent duty guidance",
        "publisher": "Home Office",
        "jurisdiction": "England",
        "source_type": "practice_guidance",
        "url": "https://www.gov.uk/government/publications/prevent-duty-guidance",
        "last_checked": "2026-05-01",
        "applies_to": ["radicalisation", "prevent"],
        "exact_text_available": False,
        "summary_basis": "Radicalisation concerns and Channel/prevent routes — not statutory children's homes law.",
        "when_to_cite": ["radicalisation", "prevent concern"],
        "scenario_families": ["safeguarding_disclosure"],
        "regulation_numbers": [],
        "citation_labels": ["Prevent guidance"],
        "confidence": "medium",
        "must_not_overclaim": "Practice guidance — do not treat as children's homes regulation.",
    },
    {
        "source_id": "nice_looked_after_children",
        "label": "NICE — Looked-after children and young people",
        "title": "Looked-after children and young people",
        "publisher": "NICE",
        "jurisdiction": "England",
        "source_type": "practice_guidance",
        "url": "https://www.nice.org.uk/guidance/ng76",
        "last_checked": "2026-05-01",
        "applies_to": ["health", "promoting wellbeing"],
        "exact_text_available": False,
        "summary_basis": "Health and wellbeing practice guidance for looked-after children.",
        "when_to_cite": ["health promotion", "CAMHS", "wellbeing"],
        "scenario_families": ["medication_health"],
        "regulation_numbers": [],
        "citation_labels": ["NICE looked-after children"],
        "confidence": "medium",
        "must_not_overclaim": "Clinical guidance — not a substitute for medical advice.",
    },
    {
        "source_id": "nice_self_harm",
        "label": "NICE — Self-harm",
        "title": "Self-harm: assessment, management and preventing recurrence",
        "publisher": "NICE",
        "jurisdiction": "England",
        "source_type": "practice_guidance",
        "url": "https://www.nice.org.uk/guidance/ng225",
        "last_checked": "2026-05-01",
        "applies_to": ["self_harm", "mental_health_crisis"],
        "exact_text_available": False,
        "summary_basis": "Self-harm assessment and management — clinical boundary applies.",
        "when_to_cite": ["self-harm", "ligature", "mental health crisis"],
        "scenario_families": ["safeguarding_disclosure", "medication_health"],
        "regulation_numbers": [],
        "citation_labels": ["NICE self-harm guidance"],
        "confidence": "medium",
        "must_not_overclaim": "Not statutory; urgent medical/mental health routes may still apply.",
    },
    {
        "source_id": "provider_safeguarding_policy",
        "label": "Provider safeguarding policy",
        "title": "Provider uploaded safeguarding policy",
        "publisher": "Provider",
        "jurisdiction": "England",
        "source_type": "provider_policy",
        "url": "",
        "last_checked": "",
        "applies_to": ["provider_specific_escalation", "local_thresholds"],
        "exact_text_available": False,
        "summary_basis": "Cite only when uploaded in standalone context — not live OS records.",
        "when_to_cite": ["safeguarding process", "internal escalation"],
        "scenario_families": ["safeguarding_disclosure"],
        "regulation_numbers": [],
        "citation_labels": ["Provider safeguarding policy"],
        "confidence": "medium",
        "must_not_overclaim": "Do not claim policy content unless user uploaded it.",
    },
    {
        "source_id": "provider_medication_policy",
        "label": "Provider medication policy",
        "title": "Provider uploaded medication policy",
        "publisher": "Provider",
        "jurisdiction": "England",
        "source_type": "provider_policy",
        "url": "",
        "applies_to": ["medication", "controlled_drugs", "PRN"],
        "exact_text_available": False,
        "summary_basis": "Medication administration and recording — provider-specific when uploaded.",
        "when_to_cite": ["medication error", "medication refusal", "controlled drug"],
        "scenario_families": ["medication_health"],
        "regulation_numbers": ["Reg 12", "Reg 13"],
        "citation_labels": ["Provider medication policy"],
        "confidence": "medium",
        "must_not_overclaim": "Do not invent policy steps.",
    },
    {
        "source_id": "provider_restraint_policy",
        "label": "Provider restraint/behaviour policy",
        "title": "Provider uploaded restraint and behaviour support policy",
        "publisher": "Provider",
        "jurisdiction": "England",
        "source_type": "provider_policy",
        "url": "",
        "applies_to": ["restraint", "restrictive_practice", "debrief"],
        "exact_text_available": False,
        "summary_basis": "Provider-specific restraint and behaviour support expectations.",
        "when_to_cite": ["physical intervention", "restraint", "debrief"],
        "scenario_families": ["behaviour_restraint"],
        "regulation_numbers": ["Reg 12"],
        "citation_labels": ["Provider restraint policy"],
        "confidence": "medium",
        "must_not_overclaim": "Do not claim live policy checked.",
    },
    {
        "source_id": "provider_missing_policy",
        "label": "Provider missing from care policy",
        "title": "Provider uploaded missing from care policy",
        "publisher": "Provider",
        "jurisdiction": "England",
        "source_type": "provider_policy",
        "url": "",
        "applies_to": ["missing", "return", "notifications"],
        "exact_text_available": False,
        "summary_basis": "Provider missing protocols when uploaded.",
        "when_to_cite": ["missing episode", "return conversation"],
        "scenario_families": ["missing_exploitation"],
        "regulation_numbers": [],
        "citation_labels": ["Provider missing policy"],
        "confidence": "medium",
        "must_not_overclaim": "Upload required for exact policy citation.",
    },
    {
        "source_id": "academy_nvq_source_pack",
        "label": "Academy/NVQ qualification criteria",
        "title": "ORB Academy/NVQ authenticity and evidence mapping pack",
        "publisher": "IndiCare ORB / sector standards",
        "jurisdiction": "England",
        "source_type": "sector_resource",
        "url": "",
        "applies_to": ["nvq", "reflective_account", "witness_testimony", "authenticity"],
        "exact_text_available": False,
        "summary_basis": "Workforce learning evidence boundaries — not legal source of truth.",
        "when_to_cite": ["nvq reflective account", "assessor discussion", "Level 3/5 evidence"],
        "scenario_families": ["academy_nvq"],
        "regulation_numbers": [],
        "citation_labels": ["Academy/NVQ pack"],
        "confidence": "high",
        "must_not_overclaim": "Supports learning evidence mapping; does not replace awarding body criteria.",
    },
    {
        "source_id": "skills_for_care_workforce",
        "label": "Skills for Care workforce resources",
        "title": "Skills for Care — sector workforce resources",
        "publisher": "Skills for Care",
        "jurisdiction": "England",
        "source_type": "sector_resource",
        "url": "https://www.skillsforcare.org.uk",
        "last_checked": "2026-05-01",
        "applies_to": ["workforce_development", "supervision", "training"],
        "exact_text_available": False,
        "summary_basis": "Sector workforce development — practice support, not law.",
        "when_to_cite": ["training gap", "supervision", "competency"],
        "scenario_families": ["academy_nvq", "management_governance"],
        "regulation_numbers": [],
        "citation_labels": ["Skills for Care"],
        "confidence": "medium",
        "must_not_overclaim": "Sector resource — not statutory.",
    },
]
