THERAPEUTIC_LANGUAGE_MODULE = {
    "residential_recording_discipline": {
        "description": "Shared wording discipline for residential records — child voice, adult action, outcome and follow-up.",
        "principles": [
            "Record behaviour as communication where appropriate.",
            "Name adult actions specifically, not just 'staff supported'.",
            "Include outcome and next steps where known.",
            "State when information is unknown rather than inventing it.",
            "Keep records factual, warm and child-centred.",
            "Separate observation from interpretation.",
            "What did the child say, show or communicate?",
            "What was the child's experience before, during and after adult support?",
            "Were the child's wishes, feelings or views known, unknown or still to be sought?",
            "What did adults do first? How did adults communicate?",
            "How did adults preserve dignity, safety and relationship?",
            "Did adults offer space, choice, reassurance, co-regulation or repair?",
            "Did adults follow plans, risk assessments, routines or agreed strategies?",
            "Did adults inform the right person, hand over or seek oversight?",
            "What appeared to help or not help? What should adults do next?",
            "Name adult actions specifically — avoid vague 'staff supported' unless support is described.",
            "Keep wording factual and proportionate. Do not make adults sound perfect or heroic.",
            "Do not blame the child. Do not invent actions not in the input.",
            "If adult response is missing, prompt for it rather than fabricate it.",
            "Reframe judgemental rough-note wording into observable, respectful language.",
            "Avoid labels such as manipulative, attention-seeking or kicked off — describe what was seen and heard.",
            "When Magic Notes receives poor wording, separate observation from interpretation.",
            "Use 'appeared', 'presented as', 'said', 'showed', 'communicated through', 'staff observed', 'not yet known' where appropriate.",
            "Do not invent the child's feelings or over-interpret behaviour.",
            "Adults remain responsible for professional judgement and safeguarding decisions.",
            "Follow local safeguarding procedures; advise escalation without making the safeguarding decision.",
            "Do not conclude 'no safeguarding concern' — record what is known and what remains unclear.",
        ],
        "structure_steps": [
            "What happened?",
            "What did the child say, show or communicate?",
            "What did adults observe?",
            "What did adults do to support?",
            "What changed by the end?",
            "What follow-up, oversight or escalation is needed?",
        ],
    },
    "principles": {
        "description": "Therapeutic language in residential care is a way of speaking that supports emotional safety, attunement, and predictability without becoming therapy.",
        "elements": [
            "Attunement: matching tone, pace, and emotional temperature.",
            "Containment: steady, grounded communication that reduces intensity.",
            "Curiosity: gentle wondering without assumptions.",
            "Validation: acknowledging feelings without interpreting them.",
            "Neutrality: avoiding judgement or emotional loading.",
            "Boundaries: clarity about roles, expectations, and safety.",
            "Predictability: clear explanations of what will happen next.",
        ],
    },
    "attuned_communication": {
        "description": "Attuned communication helps young people feel seen and safe.",
        "staff_actions": [
            "Use a calm, steady tone even when emotions are high.",
            "Match pace to the young person’s regulation level.",
            "Keep sentences short and simple.",
            "Use softening phrases such as ‘It sounds like…’ or ‘I can see this is a lot right now.’",
            "Avoid sarcasm, sharpness, or emotional intensity.",
        ],
    },
    "validation": {
        "description": "Validation acknowledges feelings without interpreting or exploring them.",
        "examples": [
            "‘It makes sense this feels difficult.’",
            "‘I can see this is important to you.’",
            "‘It looks like this has taken a lot out of you.’",
            "‘Anyone might feel unsettled in a moment like this.’",
        ],
    },
    "curiosity": {
        "description": "Curiosity helps staff understand context without assuming meaning.",
        "examples": [
            "‘I’m wondering what might help right now.’",
            "‘What do you think would make this feel a bit easier?’",
            "‘What’s the part that feels hardest at the moment?’",
            "‘What would be a good first step for you?’",
        ],
    },
    "containment": {
        "description": "Containment helps young people feel emotionally held without crossing into therapy.",
        "examples": [
            "‘You’re not on your own with this.’",
            "‘We can take this one step at a time.’",
            "‘Let’s slow things down a little.’",
            "‘I’m here and we can figure out the next bit together.’",
            "‘Let’s focus on what’s happening right now.’",
        ],
    },
    "predictability": {
        "description": "Predictability reduces anxiety and overwhelm.",
        "examples": [
            "‘Here’s what’s going to happen next…’",
            "‘I’ll let you know before anything changes.’",
            "‘We’ll take this slowly.’",
            "‘You’ll have time to think about it.’",
        ],
    },
    "boundaried_warmth": {
        "description": "Warmth is safe when paired with boundaries.",
        "examples": [
            "‘I care about how you’re feeling, and I’m here in my role to support you.’",
            "‘I want to understand what you need, and I’ll stay with you while we work it out.’",
            "‘I can’t do X, but I can help with Y.’",
            "‘I’ll stay steady even if things feel big.’",
        ],
    },
    "repair_language": {
        "description": "Repair language helps maintain trust after tension.",
        "examples": [
            "‘That moment felt tough for both of us.’",
            "‘I’m still here, and we can reset.’",
            "‘Let’s take a breath and start again.’",
            "‘We can figure out the next step together.’",
        ],
    },
    "staff_self_regulation": {
        "description": "Staff can model regulation through their own language.",
        "examples": [
            "‘I’m going to slow myself down a bit.’",
            "‘I’m taking a breath so I can stay steady with you.’",
            "‘I want to make sure I’m hearing you clearly.’",
            "‘Let’s pause for a moment.’",
        ],
    },
    "what_it_is_not": {
        "description": "Therapeutic language avoids clinical or therapeutic drift.",
        "not_allowed": [
            "Analysing emotions.",
            "Exploring trauma.",
            "Interpreting behaviour.",
            "Giving coping strategies.",
            "Offering therapy.",
            "Discussing past experiences.",
            "Giving direct instructions to the child.",
        ],
    },
}
