'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { Bot, Briefcase, Shield, Sparkles, TrendingUp, TriangleAlert } from 'lucide-react'

import { FounderNavHeader } from '@/components/founder/founder-nav-header'
import { getTopFounderActions } from '@/lib/founder/actions'
import type { FounderActionStatus } from '@/lib/founder/actions'
import { FounderActionCard } from '@/components/founder/founder-action-card'
import {
  getChiefOfStaffBriefing,
  getFounderContractInputs,
  getFounderTelemetrySummaryForDashboard,
  hasLiveFounderIntelligence,
  refreshFounderDashboardData
} from '@/lib/founder/intelligence-service'
import { calculateAiCost, calculateHoursReturned, calculateOfstedReadiness } from '@/lib/founder/intelligence'
import { runGrowthAgent } from '@/lib/founder/agents/growth-agent'
import { runProductAgent } from '@/lib/founder/agents/product-agent'
import { runSectorIntelligenceAgent } from '@/lib/founder/agents/sector-intelligence-agent'

function getGreeting() {
  const hour = new Date().getHours()
  if (hour < 12) return 'Good Morning'
  if (hour < 17) return 'Good Afternoon'
  return 'Good Evening'
}

const WAITING_MESSAGE =
  'This briefing is waiting for live founder data. Connect live usage, revenue, ORB analytics and readiness sources to generate a real briefing.'

export function FounderBriefingPage() {
  const [, setTick] = useState(0)
  const refresh = useCallback(() => setTick((t) => t + 1), [])
  const [hasLive, setHasLive] = useState(() => hasLiveFounderIntelligence())

  useEffect(() => {
    let active = true
    refreshFounderDashboardData()
      .then(() => {
        if (active) setHasLive(hasLiveFounderIntelligence())
      })
      .catch(() => undefined)
    return () => {
      active = false
    }
  }, [])

  const todaysActions = getTopFounderActions(5)
  const briefing = getChiefOfStaffBriefing()
  const product = runProductAgent()
  const growth = runGrowthAgent()
  const sector = runSectorIntelligenceAgent()
  const contractInputs = getFounderContractInputs()
  const readiness = hasLive ? calculateOfstedReadiness(contractInputs.readinessMetrics) : null
  const aiCost = hasLive ? calculateAiCost(contractInputs.billingMetrics) : null
  const hoursReturned = hasLive
    ? calculateHoursReturned(contractInputs.usageMetrics, contractInputs.orbConversationAnalytics)
    : null
  const { providerAnalytics } = contractInputs
  const telemetry = getFounderTelemetrySummaryForDashboard()

  const snapshotSections = hasLive
    ? [
        {
          icon: TrendingUp,
          title: 'Revenue',
          tone: 'text-emerald-300',
          content: `MRR at £${providerAnalytics.totalMrr.toLocaleString('en-GB')} (${providerAnalytics.mrrTrendPercent >= 0 ? '+' : ''}${providerAnalytics.mrrTrendPercent}% MoM). ${providerAnalytics.totalProviders} providers across ${providerAnalytics.totalHomes} homes.${aiCost ? ` Gross margin ${aiCost.grossMargin}.` : ''}`
        },
        {
          icon: Briefcase,
          title: 'Growth',
          tone: 'text-cyan-300',
          content: growth.summary
        },
        {
          icon: Sparkles,
          title: 'Product',
          tone: 'text-violet-300',
          content: product.summary
        },
        {
          icon: TriangleAlert,
          title: 'Risk',
          tone: 'text-amber-300',
          content: readiness && aiCost
            ? `Platform readiness at ${readiness.score}% (${readiness.status}). AI spend ${aiCost.openAiSpend} — ${aiCost.usageWarningLabel}. ${readiness.gaps.filter((g) => g.severity === 'critical').length} critical readiness gaps.`
            : 'Live risk signals require connected readiness and AI usage sources.'
        },
        {
          icon: Shield,
          title: 'Sector Trends',
          tone: 'text-rose-300',
          content: sector.summary
        }
      ]
    : []

  return (
    <div className="founder-dashboard min-h-screen">
      <div className="founder-dashboard-bg pointer-events-none fixed inset-0 -z-10" aria-hidden />

      <div className="mx-auto max-w-[1000px] space-y-8 px-4 py-8 pb-16 md:px-8">
        <FounderNavHeader
          title={`${getGreeting()}, Thomas`}
          subtitle="Your daily intelligence briefing, generated by the Chief of Staff Agent from live platform signals only."
        />

        <div className="founder-surface rounded-2xl border border-white/10 bg-white/[0.04] px-6 py-4">
          {!hasLive ? (
            <p className="text-sm leading-7 text-amber-200/90">{WAITING_MESSAGE}</p>
          ) : null}
          {hasLive && hoursReturned && hoursReturned.totalHours > 0 ? (
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-semibold text-slate-400">
              <span className="h-2 w-2 rounded-full bg-emerald-400" />
              {hoursReturned.totalHoursFormatted} hours returned to direct care this month
            </div>
          ) : null}
          {telemetry.totalEvents > 0 ? (
            <p className="mt-3 text-sm text-slate-400">
              Live telemetry: {telemetry.eventsToday} events today · {telemetry.orbConversations} ORB conversations ·{' '}
              {telemetry.feedbackCount} feedback signals
              {telemetry.lastUpdated ? ` · updated ${new Date(telemetry.lastUpdated).toLocaleString('en-GB')}` : ''}
            </p>
          ) : null}
          <Link
            href="/founder/orb"
            className="mt-4 inline-flex items-center gap-2 rounded-xl border border-violet-400/30 bg-violet-500/10 px-4 py-2.5 text-sm font-bold text-violet-200 transition hover:border-violet-400/50 hover:bg-violet-500/15"
          >
            <Bot className="h-4 w-4" aria-hidden />
            Ask ORB Founder
          </Link>
        </div>

        {!hasLive ? (
          <section className="founder-surface rounded-[28px] border border-amber-400/20 bg-amber-500/5 p-8 backdrop-blur-xl">
            <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-amber-300">Awaiting live data</p>
            <p className="mt-4 text-base leading-8 text-slate-300">{WAITING_MESSAGE}</p>
          </section>
        ) : (
          <section className="founder-surface rounded-[28px] border border-white/10 bg-white/[0.04] p-8 backdrop-blur-xl">
            <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Today&apos;s Snapshot</p>
            <div className="mt-6 space-y-5">
              {snapshotSections.map((section) => (
                <article key={section.title} className="rounded-2xl border border-white/8 bg-black/20 p-5">
                  <div className="flex items-center gap-3">
                    <section.icon className={`h-5 w-5 ${section.tone}`} aria-hidden />
                    <h2 className="text-sm font-bold uppercase tracking-[0.14em] text-white">{section.title}</h2>
                  </div>
                  <p className="mt-3 text-sm leading-7 text-slate-300">{section.content}</p>
                </article>
              ))}
            </div>
          </section>
        )}

        <section className="founder-surface rounded-[28px] border border-cyan-400/20 bg-gradient-to-br from-cyan-500/5 to-transparent p-8 backdrop-blur-xl">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-cyan-300">Chief of Staff Summary</p>
          <h2 className="mt-3 text-2xl font-bold text-white">{briefing.title}</h2>
          <p className="mt-4 text-base leading-8 text-slate-300">{briefing.summary}</p>
        </section>

        {hasLive && todaysActions.length > 0 ? (
          <section className="founder-surface rounded-[28px] border border-emerald-400/20 bg-gradient-to-br from-emerald-500/5 to-transparent p-8 backdrop-blur-xl">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-300">Today&apos;s Founder Actions</p>
              <Link
                href="/founder/actions"
                className="text-xs font-bold text-emerald-200 transition hover:text-emerald-100"
              >
                View all actions
              </Link>
            </div>
            <div className="mt-6 space-y-4">
              {todaysActions.map((action) => (
                <FounderActionCard
                  key={action.id}
                  action={action}
                  compact
                  onStatusChange={(_id: string, _status: FounderActionStatus) => refresh()}
                />
              ))}
            </div>
          </section>
        ) : null}

        {hasLive && briefing.recommendations.length > 0 ? (
          <section className="founder-surface rounded-[28px] border border-white/10 bg-white/[0.04] p-8 backdrop-blur-xl">
            <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Recommended Actions</p>
            <ol className="mt-6 space-y-4">
              {briefing.recommendations.map((action, index) => (
                <li key={action} className="flex items-start gap-4 rounded-2xl border border-white/8 bg-black/20 p-5">
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-violet-400/30 bg-violet-500/10 text-sm font-black text-violet-200">
                    {index + 1}
                  </span>
                  <p className="text-sm leading-7 text-slate-200">{action}</p>
                </li>
              ))}
            </ol>
          </section>
        ) : null}

        <p className="text-center text-xs text-slate-600">
          Generated {new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
          {' · '}
          IndiCare Intelligence Operating System
        </p>
      </div>
    </div>
  )
}
