'use client'

import Link from 'next/link'
import { ArrowLeft, Bot, Briefcase, Shield, Sparkles, TrendingUp, TriangleAlert } from 'lucide-react'

import { getChiefOfStaffBriefing, getFounderContractInputs } from '@/lib/founder/intelligence-service'
import { calculateAiCost, calculateHoursReturned, calculateOfstedReadiness } from '@/lib/founder/intelligence'
import { runGrowthAgent } from '@/lib/founder/agents/growth-agent'
import { runProductAgent } from '@/lib/founder/agents/product-agent'
import { runSectorIntelligenceAgent } from '@/lib/founder/agents/sector-intelligence-agent'

function getGreeting() {
  const hour = new Date().getHours()
  if (hour < 12) return 'Good Morning'
  if (hour < 17) return 'Good Afternoon'
  return 'Good Evening'
}

export function FounderBriefingPage() {
  const briefing = getChiefOfStaffBriefing()
  const product = runProductAgent()
  const growth = runGrowthAgent()
  const sector = runSectorIntelligenceAgent()
  const contractInputs = getFounderContractInputs()
  const readiness = calculateOfstedReadiness(contractInputs.readinessMetrics)
  const aiCost = calculateAiCost(contractInputs.billingMetrics)
  const hoursReturned = calculateHoursReturned(
    contractInputs.usageMetrics,
    contractInputs.orbConversationAnalytics
  )
  const { providerAnalytics, dataSourceStatus } = contractInputs

  const snapshotSections = [
    {
      icon: TrendingUp,
      title: 'Revenue',
      tone: 'text-emerald-300',
      content: `MRR at £${providerAnalytics.totalMrr.toLocaleString('en-GB')} (+${providerAnalytics.mrrTrendPercent}% MoM). ${providerAnalytics.totalProviders} providers across ${providerAnalytics.totalHomes} homes. Gross margin ${aiCost.grossMargin}.`
    },
    {
      icon: Briefcase,
      title: 'Growth',
      tone: 'text-cyan-300',
      content: growth.summary
    },
    {
      icon: Sparkles,
      title: 'Product',
      tone: 'text-violet-300',
      content: product.summary
    },
    {
      icon: TriangleAlert,
      title: 'Risk',
      tone: 'text-amber-300',
      content: `Platform readiness at ${readiness.score}% (${readiness.status}). AI spend ${aiCost.openAiSpend} — ${aiCost.usageWarningLabel}. ${readiness.gaps.filter((g) => g.severity === 'critical').length} critical readiness gaps.`
    },
    {
      icon: Shield,
      title: 'Sector Trends',
      tone: 'text-rose-300',
      content: sector.summary
    }
  ]

  return (
    <div className="founder-dashboard min-h-screen">
      <div className="founder-dashboard-bg pointer-events-none fixed inset-0 -z-10" aria-hidden />

      <div className="mx-auto max-w-[1000px] space-y-8 px-4 py-8 pb-16 md:px-8">
        <Link
          href="/founder"
          className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-300 transition hover:text-cyan-200"
        >
          <ArrowLeft className="h-4 w-4" aria-hidden />
          Back to Command Centre
        </Link>

        <header className="founder-surface rounded-[32px] border border-white/10 bg-white/[0.04] p-8 shadow-[0_28px_90px_rgba(0,0,0,0.45)] backdrop-blur-xl">
          <div className="flex flex-wrap items-start justify-between gap-6">
            <div>
              <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-cyan-300">Private Executive Briefing</p>
              <h1 className="mt-4 text-4xl font-black tracking-[-0.05em] text-white md:text-5xl">
                {getGreeting()}, Thomas
              </h1>
              <p className="mt-4 max-w-2xl text-base leading-7 text-slate-400">
                Your daily intelligence briefing, generated by the Chief of Staff Agent from{' '}
                {dataSourceStatus.source === 'live' ? 'live' : dataSourceStatus.source === 'hybrid' ? 'hybrid' : 'estimated'}{' '}
                platform signals.
              </p>
              {dataSourceStatus.source !== 'live' ? (
                <p className="mt-3 text-sm text-amber-200/90">
                  Some figures in this briefing are estimated or mocked until all live data sources are connected.
                </p>
              ) : null}
              <div className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/30 px-4 py-2 text-xs font-semibold text-slate-400">
                <span className="h-2 w-2 rounded-full bg-emerald-400" />
                {hoursReturned.totalHoursFormatted} hours returned to direct care this month
              </div>
            </div>
            <Link
              href="/founder/orb"
              className="inline-flex items-center gap-2 rounded-xl border border-violet-400/30 bg-violet-500/10 px-4 py-2.5 text-sm font-bold text-violet-200 transition hover:border-violet-400/50 hover:bg-violet-500/15"
            >
              <Bot className="h-4 w-4" aria-hidden />
              Ask ORB Founder
            </Link>
          </div>
        </header>

        <section className="founder-surface rounded-[28px] border border-white/10 bg-white/[0.04] p-8 backdrop-blur-xl">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Today&apos;s Snapshot</p>
          <div className="mt-6 space-y-5">
            {snapshotSections.map((section) => (
              <article key={section.title} className="rounded-2xl border border-white/8 bg-black/20 p-5">
                <div className="flex items-center gap-3">
                  <section.icon className={`h-5 w-5 ${section.tone}`} aria-hidden />
                  <h2 className="text-sm font-bold uppercase tracking-[0.14em] text-white">{section.title}</h2>
                </div>
                <p className="mt-3 text-sm leading-7 text-slate-300">{section.content}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="founder-surface rounded-[28px] border border-cyan-400/20 bg-gradient-to-br from-cyan-500/5 to-transparent p-8 backdrop-blur-xl">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-cyan-300">Chief of Staff Summary</p>
          <h2 className="mt-3 text-2xl font-bold text-white">{briefing.title}</h2>
          <p className="mt-4 text-base leading-8 text-slate-300">{briefing.summary}</p>
        </section>

        <section className="founder-surface rounded-[28px] border border-white/10 bg-white/[0.04] p-8 backdrop-blur-xl">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-500">Recommended Actions</p>
          <ol className="mt-6 space-y-4">
            {briefing.recommendations.map((action, index) => (
              <li key={action} className="flex items-start gap-4 rounded-2xl border border-white/8 bg-black/20 p-5">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-violet-400/30 bg-violet-500/10 text-sm font-black text-violet-200">
                  {index + 1}
                </span>
                <p className="text-sm leading-7 text-slate-200">{action}</p>
              </li>
            ))}
          </ol>
        </section>

        <p className="text-center text-xs text-slate-600">
          Generated {new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}
          {' · '}
          IndiCare Intelligence Operating System
        </p>
      </div>
    </div>
  )
}
