const alertsNav = document.getElementById("workspace-nav");
const alertsMain = document.getElementById("workspace-main");
const alertsTitle = document.getElementById("view-title");
const alertsSubtitle = document.getElementById("view-subtitle");
const alertsOutput = document.getElementById("assistant-output");

if (alertsNav) {
  alertsNav.addEventListener("click", (event) => {
    const button = event.target.closest("button[data-view='alerts']");
    if (!button) return;
    event.preventDefault();
    event.stopImmediatePropagation();
    document.querySelectorAll(".nav-item").forEach((item) => item.classList.remove("active"));
    button.classList.add("active");
    renderAlertsWorkspace();
  }, true);
}

window.renderAlertsWorkspace = renderAlertsWorkspace;

async function renderAlertsWorkspace() {
  if (alertsTitle) alertsTitle.textContent = "Alerts and escalation";
  if (alertsSubtitle) alertsSubtitle.textContent = "Active risk, safeguarding, evidence and workflow alerts requiring human review.";
  if (!alertsMain) return;

  alertsMain.innerHTML = `<div class="skeleton"><span></span><span></span><span></span></div>`;

  const data = await getJson("/alerts/active");
  if (!data?.ok) {
    alertsMain.innerHTML = `<div class="warning-banner">${escapeHtml(data?.detail || data?.error || "Could not load alerts.")}</div>`;
    return;
  }

  const summary = data.summary || {};
  const alerts = data.alerts || [];

  alertsMain.innerHTML = `
    <section class="hero-card">
      <div>
        <p class="eyebrow">Live alerting</p>
        <h3>Active alerts</h3>
        <p>Alerts are generated from proactive, predictive and persistent alert sources.</p>
      </div>
      <span class="score-pill">${escapeHtml(summary.total || 0)} active</span>
    </section>

    <section class="card-grid">
      ${metric("Critical", summary.critical || 0, "Immediate review")}
      ${metric("High", summary.high || 0, "Prioritise today")}
      ${metric("Medium", summary.medium || 0, "Needs attention")}
      ${metric("Low", summary.low || 0, "Monitor")}
    </section>

    <section class="record-list alerts-list">
      ${alerts.length ? alerts.map(renderAlertCard).join("") : `<div class="empty-state">No active alerts.</div>`}
    </section>
  `;

  alertsMain.querySelectorAll("[data-alert-action]").forEach((button) => {
    button.addEventListener("click", () => handleAlertAction(button.dataset.alertAction, button.dataset.alertId));
  });
}

function renderAlertCard(alert) {
  const id = alert.id || "generated-alert";
  const level = alert.level || "low";
  return `
    <article class="record-card alert-card ${escapeHtml(level)}">
      <div>
        <div class="review-meta">
          <span class="mini-tag">${escapeHtml(level)} severity</span>
          <span class="mini-tag">${escapeHtml(alert.category || "alert")}</span>
          <span class="mini-tag">${escapeHtml(alert.status || "active")}</span>
        </div>
        <h4>${escapeHtml(alert.title || "Alert")}</h4>
        <p>${escapeHtml(alert.message || "Alert generated by IndiCare.")}</p>
        <div class="review-why"><strong>Why this matters:</strong> ${escapeHtml(alert.why || "Requires human review.")}</div>
        <small>${escapeHtml(alert.recommended_action || "Review source records and decide next steps.")}</small>
      </div>
      <div class="record-actions">
        <button type="button" data-alert-action="acknowledge" data-alert-id="${escapeHtml(id)}">Acknowledge</button>
        <button type="button" data-alert-action="escalate" data-alert-id="${escapeHtml(id)}">Escalate</button>
      </div>
    </article>
  `;
}

async function handleAlertAction(action, alertId) {
  const comment = prompt(action === "escalate" ? "Escalation note" : "Acknowledgement note") || "";
  const endpoint = action === "escalate" ? `/alerts/${encodeURIComponent(alertId)}/escalate` : `/alerts/${encodeURIComponent(alertId)}/acknowledge`;
  const data = await postJson(endpoint, { comment });
  if (!data?.ok) {
    toast(data?.detail || data?.error || "Alert action failed.");
    return;
  }
  toast(`Alert ${action} recorded.`);
  renderAlertsWorkspace();
}

function metric(label, value, help) {
  return `<article class="metric-card"><strong>${escapeHtml(value)}</strong><span>${escapeHtml(label)}</span><small>${escapeHtml(help)}</small></article>`;
}

async function getJson(url) {
  try {
    const response = await fetch(url, { credentials: "include" });
    return await response.json();
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

async function postJson(url, payload) {
  try {
    const response = await fetch(url, {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    return await response.json();
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

function toast(message) {
  if (alertsOutput) alertsOutput.innerHTML = `<p>${escapeHtml(message)}</p>`;
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
}
