window.IndiCareOSData=(function(){
  const fallbackYoungPerson={id:1,first_name:'Jamie',last_name:'Smith',age:15,summary_risk_level:'Medium',key_worker:'Sarah',placement_status:'Stable'};
  const fallback={
    people:[fallbackYoungPerson],
    daily:[{record_type:'Daily note',title:'Settled evening routine',summary:'Young person presented as calm and engaged with staff.',date:'Today',status:'Recorded'}],
    incidents:[{record_type:'Incident',title:'Physical aggression after phone call',summary:'Incident followed emotional trigger. Staff response recorded.',date:'04 May 2026',status:'Manager review required',level:'warning'}],
    risk:[{area:'Aggression',level:'Medium'},{area:'Missing from care',level:'Low'},{area:'Self-harm',level:'Medium'},{area:'Exploitation',level:'Low'}],
    safeguarding:[{title:'Online contact concern',summary:'Unknown adult contact reported. Manager oversight required.',level:'high'}],
    inspection:{score:82,domains:[['Help & Protection',12,80],['Education',8,70],['Health',6,60],['Leadership',10,85]],gaps:[['Safeguarding follow-up','Missing manager commentary','warning'],['Risk review','Overdue update','critical']]},
    actions:[{id:'demo-1',title:'Manager review required',summary:'Review linked record and confirm follow-up.',status:'open',priority:'high',due_date:'Today'}]
  };
  const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
  async function request(url,options={}){try{const r=await fetch(url,{credentials:'include',headers:{Accept:'application/json','Content-Type':'application/json',...(options.headers||{})},cache:'no-store',...options});if(!r.ok)return null;return await r.json()}catch{return null}}
  async function get(url){return request(url)}
  async function post(url,body){return request(url,{method:'POST',body:JSON.stringify(body||{})})}
  async function patch(url,body){return request(url,{method:'PATCH',body:JSON.stringify(body||{})})}
  function arr(v){return Array.isArray(v)?v:Array.isArray(v?.items)?v.items:Array.isArray(v?.actions)?v.actions:Array.isArray(v?.data)?v.data:Array.isArray(v?.results)?v.results:[]}
  function name(p){return p?.preferred_name||p?.name||p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||`Young person ${p?.id||''}`}
  function id(p){return p?.id||p?.young_person_id||p?.person_id||1}
  async function getPeople(){const data=await get('/young-people');const people=arr(data);return people.length?people:fallback.people}
  async function getSelectedPerson(){const people=await getPeople();return people[0]||fallbackYoungPerson}
  async function getChildBundle(personId){const urls=['daily-notes','incidents','health','education','family','risk','safeguarding','missing-episodes','documents'].map(x=>`/young-people/${personId}/${x}`);const keys=['daily','incidents','health','education','family','riskRecords','safeguarding','missing','documents'];const out={};await Promise.all(urls.map(async(u,i)=>{out[keys[i]]=arr(await get(u));}));return out}
  async function getInspection(homeId=1){const scores=await get(`/homes/${homeId}/inspection-scores`);const sections=await get(`/homes/${homeId}/inspection-section-scores`);const actions=await get(`/homes/${homeId}/inspection-improvement-actions`);return{scores:arr(scores),sections:arr(sections),actions:arr(actions)}}
  async function getActions(params={}){const qs=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')qs.set(k,v)});const data=await get(`/actions/${qs.toString()?`?${qs}`:''}`);const actions=arr(data);return actions.length?actions:fallback.actions}
  async function createAction(payload){const data=await post('/actions/',payload);return data?.item||data?.action||null}
  async function updateAction(id,payload){const data=await patch(`/actions/${id}`,payload);return data?.item||data?.action||null}
  function recordCard(r){const title=r.title||r.summary||r.incident_type||r.record_type||'Care record';const summary=r.summary||r.presentation||r.action_taken||r.outcome||r.detail||'No further detail recorded.';const type=r.record_type||r.source_table||'Record';const status=r.status||r.workflow_status||r.approval_status||'';const date=r.date||r.note_date||r.created_at||r.incident_datetime||r.event_datetime||'';const recordId=r.id||r.record_id||r.source_id||'';return`<article class="ic-record" data-record-id="${esc(recordId)}" data-record-type="${esc(type)}"><div class="ic-record-type">${esc(type)}</div><h3>${esc(title)}</h3><p>${esc(summary)}</p><div class="ic-record-actions"><span class="ic-chip">${esc(status||'Open')}</span>${date?`<span class="ic-chip">${esc(date)}</span>`:''}<button class="ic-btn primary" type="button" data-os-action="open">Open</button><button class="ic-btn" type="button" data-os-action="add-action">Add action</button></div></article>`}
  function actionCard(a){return`<article class="ic-record"><div class="ic-record-type">${esc(a.priority||'Action')}</div><h3>${esc(a.title||'Action')}</h3><p>${esc(a.summary||a.task||'')}</p><div class="ic-record-actions"><span class="ic-chip">${esc(a.status||'open')}</span>${a.due_date?`<span class="ic-chip">Due ${esc(a.due_date)}</span>`:''}<button class="ic-btn primary" type="button" data-complete-action="${esc(a.id)}">Complete</button></div></article>`}
  function ensureActionModal(){let modal=document.getElementById('icActionModal');if(modal)return modal;modal=document.createElement('div');modal.id='icActionModal';modal.className='ic-modal';modal.innerHTML=`<div class="ic-modal-panel"><div class="ic-modal-head"><div><h2>Create action</h2><p id="icActionContext" class="ic-empty"></p></div><button class="ic-btn" type="button" id="icActionClose">Close</button></div><form class="ic-form" id="icActionForm"><label><span>Action title</span><input name="title" required /></label><label><span>Action detail</span><textarea name="task"></textarea></label><label><span>Priority</span><select name="priority"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical safeguarding</option><option value="low">Low</option></select></label><label><span>Due date</span><input name="due_date" type="date" /></label><input type="hidden" name="young_person_id" /><input type="hidden" name="source_type" /><input type="hidden" name="source_id" /><button class="ic-btn primary" type="submit">Save action</button><p id="icActionStatus" class="ic-empty"></p></form></div>`;document.body.appendChild(modal);document.getElementById('icActionClose').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});return modal}
  function openActionModal(context={},onSaved){const modal=ensureActionModal();const form=document.getElementById('icActionForm');document.getElementById('icActionContext').textContent=context.contextText||'';form.title.value=context.title||'';form.task.value=context.task||'';form.priority.value=context.priority||'medium';form.due_date.value=context.due_date||'';form.young_person_id.value=context.young_person_id||'';form.source_type.value=context.source_type||'';form.source_id.value=context.source_id||'';document.getElementById('icActionStatus').textContent='';form.onsubmit=async e=>{e.preventDefault();const payload={title:form.title.value,task:form.task.value,priority:form.priority.value,due_date:form.due_date.value||null,young_person_id:form.young_person_id.value||null,source_type:form.source_type.value||null,source_id:form.source_id.value||null,status:'open'};document.getElementById('icActionStatus').textContent='Saving action…';const saved=await createAction(payload);document.getElementById('icActionStatus').textContent=saved?'Action saved.':'Could not save action.';if(saved&&typeof onSaved==='function')onSaved(saved);};modal.classList.add('open')}
  function bindActionButtons(root=document,contextProvider){root.addEventListener('click',e=>{const btn=e.target.closest('[data-os-action="add-action"]');if(!btn)return;const card=btn.closest('.ic-record');const title=card?.querySelector('h3')?.textContent||'Follow up action';const task=card?.querySelector('p')?.textContent||'';const base=typeof contextProvider==='function'?contextProvider(card):{};openActionModal({title:`Follow up: ${title}`,task,source_type:card?.dataset.recordType||base.source_type||'',source_id:card?.dataset.recordId||base.source_id||'',...base},saved=>{btn.textContent='Action added';btn.disabled=true})})}
  return{fallback,esc,arr,name,id,get,post,patch,getPeople,getSelectedPerson,getChildBundle,getInspection,getActions,createAction,updateAction,recordCard,actionCard,openActionModal,bindActionButtons};
})();