from __future__ import annotations

import json
import re
import uuid

from docx import Document
from docx.enum.section import WD_ORIENT
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from services.ai_gateway_service import AIGatewayRequest, ai_gateway_service

router = APIRouter(prefix="/risk", tags=["Risk"])


class RiskRequest(BaseModel):
    description: str
    provider_id: int | None = None
    home_id: int | None = None
    user_id: int | None = None


def _extract_json_array(text: str) -> list[dict]:
    cleaned = (text or "").strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\[[\s\S]*\]", cleaned)
        if not match:
            raise HTTPException(status_code=502, detail="AI risk draft did not return valid JSON")
        parsed = json.loads(match.group(0))
    if not isinstance(parsed, list):
        raise HTTPException(status_code=502, detail="AI risk draft must be a JSON list")
    return [item for item in parsed if isinstance(item, dict)]


def _risk_prompt(description: str) -> str:
    return f"""
You help staff in residential children's homes draft risk assessments.

Return a structured draft risk assessment for the following situation.
This is decision-support only. Do not make final safeguarding, medical or legal decisions.
Use British English, therapeutic and child-centred language.

Return exactly 5 hazards in JSON format only:
[
  {{
    "hazard": "",
    "who_at_risk": "",
    "potential_harm": "",
    "likelihood": "",
    "severity": "",
    "controls": "",
    "further_controls": ""
  }}
]

Situation:
{description}
"""


@router.post("/generate")
def generate_risk(payload: RiskRequest):
    prompt = _risk_prompt(payload.description)
    response = ai_gateway_service.draft_text(
        AIGatewayRequest(
            feature="risk_drafting",
            prompt=prompt,
            provider_id=payload.provider_id,
            home_id=payload.home_id,
            user_id=payload.user_id,
            max_output_tokens=1400,
            metadata={"route": "/risk/generate", "draft_only": True},
        )
    )
    risks = _extract_json_array(response.text)

    doc = Document()
    section = doc.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = section.page_height, section.page_width

    doc.add_heading("IndiCare Risk Assessment", level=1)
    doc.add_paragraph("Draft generated by IndiCare AI governance gateway. Must be reviewed and signed off by a manager before use.")

    table = doc.add_table(rows=1, cols=10)
    headers = [
        "Hazard",
        "Who at Risk",
        "Potential Harm",
        "Likelihood",
        "Severity",
        "Risk Score",
        "Existing Controls",
        "Further Controls",
        "Responsible",
        "Review Date",
    ]

    for i, header in enumerate(headers):
        table.rows[0].cells[i].text = header

    for risk in risks[:5]:
        row = table.add_row().cells
        row[0].text = str(risk.get("hazard", ""))
        row[1].text = str(risk.get("who_at_risk", ""))
        row[2].text = str(risk.get("potential_harm", ""))
        row[3].text = str(risk.get("likelihood", ""))
        row[4].text = str(risk.get("severity", ""))
        row[5].text = ""
        row[6].text = str(risk.get("controls", ""))
        row[7].text = str(risk.get("further_controls", ""))
        row[8].text = ""
        row[9].text = ""

    doc.add_paragraph(
        f"AI governance: redaction_applied={response.redaction_applied}; estimated_cost_gbp={response.estimated_cost_gbp}; human_review_required=True."
    )

    filename = f"risk_{uuid.uuid4()}.docx"
    path = f"/tmp/{filename}"
    doc.save(path)

    return FileResponse(
        path,
        filename="Risk_Assessment.docx",
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
