-- IndiCare OS Command operational co-pilot layer
-- Adds contextual safeguarding summaries, operational insights and manager briefing generation.

DO $$ BEGIN
  CREATE TYPE os_copilot_summary_type AS ENUM (
    'shift_briefing',
    'manager_briefing',
    'safeguarding_summary',
    'inspection_summary',
    'risk_summary',
    'handover_summary'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.os_copilot_briefings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id int4,
  home_id int4,
  young_person_id int4,
  shift_session_id uuid REFERENCES public.os_shift_sessions(id) ON DELETE SET NULL,
  summary_type os_copilot_summary_type NOT NULL,
  title text NOT NULL,
  summary_text text NOT NULL,
  priority_level text NOT NULL DEFAULT 'medium' CHECK (priority_level IN ('low','medium','high','critical')),
  generated_from jsonb NOT NULL DEFAULT '[]'::jsonb,
  recommendations jsonb NOT NULL DEFAULT '[]'::jsonb,
  safeguarding_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  requires_manager_review boolean NOT NULL DEFAULT true,
  reviewed_by int4,
  reviewed_at timestamptz,
  created_by int4,
  created_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_os_copilot_briefings_home_created
  ON public.os_copilot_briefings(home_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.os_copilot_generate_shift_briefing(
  p_shift_session_id uuid,
  p_user_id int4 DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  v_shift public.os_shift_sessions%ROWTYPE;
  v_open_tasks int4 := 0;
  v_critical int4 := 0;
  v_missing int4 := 0;
  v_reg40 int4 := 0;
  v_summary text;
  v_id uuid;
BEGIN
  SELECT * INTO v_shift
  FROM public.os_shift_sessions
  WHERE id = p_shift_session_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Shift session not found: %', p_shift_session_id;
  END IF;

  SELECT count(*) INTO v_open_tasks
  FROM public.os_shift_tasks
  WHERE shift_session_id = p_shift_session_id
    AND status IN ('open','in_progress');

  SELECT count(*) INTO v_critical
  FROM public.os_shift_tasks
  WHERE shift_session_id = p_shift_session_id
    AND status IN ('open','in_progress')
    AND priority = 'critical';

  SELECT count(*) INTO v_missing
  FROM public.os_missing_from_care_workflows
  WHERE home_id = v_shift.home_id
    AND status IN ('open','located');

  SELECT count(*) INTO v_reg40
  FROM public.vw_os_reg40_board
  WHERE home_id = v_shift.home_id
    AND board_state IN ('required','overdue');

  v_summary := concat_ws(
    E'\n\n',
    'Shift operational briefing generated by IndiCare OS.',
    'Open operational tasks: ' || v_open_tasks,
    'Critical operational tasks: ' || v_critical,
    'Active missing-from-care episodes: ' || v_missing,
    'Outstanding Regulation 40 actions: ' || v_reg40,
    CASE
      WHEN v_critical > 0 THEN 'Immediate management attention required for critical operational items.'
      ELSE 'No critical operational concerns identified at briefing generation time.'
    END
  );

  INSERT INTO public.os_copilot_briefings (
    provider_id,
    home_id,
    shift_session_id,
    summary_type,
    title,
    summary_text,
    priority_level,
    generated_from,
    recommendations,
    safeguarding_flags,
    requires_manager_review,
    created_by
  ) VALUES (
    v_shift.provider_id,
    v_shift.home_id,
    p_shift_session_id,
    'shift_briefing',
    'Shift operational briefing',
    v_summary,
    CASE WHEN v_critical > 0 OR v_missing > 0 THEN 'high' ELSE 'medium' END,
    jsonb_build_array(
      jsonb_build_object('table','os_shift_tasks','count',v_open_tasks),
      jsonb_build_object('table','os_missing_from_care_workflows','count',v_missing),
      jsonb_build_object('table','vw_os_reg40_board','count',v_reg40)
    ),
    jsonb_build_array(
      CASE WHEN v_missing > 0 THEN 'Active missing-from-care episode present' ELSE null END,
      CASE WHEN v_reg40 > 0 THEN 'Outstanding Regulation 40 workflow present' ELSE null END
    ),
    jsonb_build_array(
      'Review safeguarding actions at shift start',
      'Ensure overdue operational tasks are prioritised',
      'Confirm handover risks have assigned owners'
    ),
    true,
    p_user_id
  ) RETURNING id INTO v_id;

  PERFORM public.os_live_emit(
    'ai.recommendation.created',
    'os_copilot_briefings',
    v_id::text,
    'Shift operational briefing generated',
    v_shift.provider_id,
    v_shift.home_id,
    NULL,
    NULL,
    jsonb_build_object('summary_type','shift_briefing','priority','high'),
    ARRAY['senior','manager'],
    p_user_id
  );

  RETURN v_id;
END;
$$;

CREATE OR REPLACE VIEW public.vw_os_copilot_manager_feed AS
SELECT
  b.id,
  b.provider_id,
  b.home_id,
  b.young_person_id,
  b.shift_session_id,
  b.summary_type::text AS summary_type,
  b.title,
  b.summary_text,
  b.priority_level,
  b.generated_from,
  b.recommendations,
  b.safeguarding_flags,
  b.requires_manager_review,
  b.reviewed_by,
  b.reviewed_at,
  b.created_at,
  CASE
    WHEN b.priority_level = 'critical' THEN 0
    WHEN b.priority_level = 'high' THEN 1
    WHEN b.priority_level = 'medium' THEN 2
    ELSE 3
  END AS priority_sort
FROM public.os_copilot_briefings b
ORDER BY priority_sort, created_at DESC;
